In [25]:
import tensorflow as tf
import numpy as np

In [26]:
from tensorflow.keras.datasets import imdb

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)



17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [44]:
print(X_train.shape)
print(X_test.shape)

(25000, 200)
(25000, 200)


array([[   5,   25,  100, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [48]:
print(X_train[0].shape)
print(y_train[0])

(200,)
1


In [46]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train = pad_sequences(
    X_train,
    maxlen=200
)

X_test = pad_sequences(
    X_test,
    maxlen=200
)


array([[   5,   25,  100, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [31]:
print(X_train.shape)

(25000, 200)


In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [33]:
model = Sequential()

In [34]:
model.add(
    Embedding(
        input_dim=10000,
        output_dim=64
    )
)

In [35]:
model.add(
    LSTM(64)
)

In [36]:
model.add(
    Dense(
        1,
        activation="sigmoid"
    )
)

In [37]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [38]:
history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 57s 174ms/step - accuracy: 0.7770 - loss: 0.4785 - val_accuracy: 0.8588 - val_loss: 0.3450
Epoch 2/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 86s 186ms/step - accuracy: 0.8917 - loss: 0.2788 - val_accuracy: 0.8558 - val_loss: 0.3382
Epoch 3/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 60s 193ms/step - accuracy: 0.9261 - loss: 0.2021 - val_accuracy: 0.8594 - val_loss: 0.3307
Epoch 4/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 58s 184ms/step - accuracy: 0.9438 - loss: 0.1569 - val_accuracy: 0.8580 - val_loss: 0.3713
Epoch 5/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 85s 194ms/step - accuracy: 0.9546 - loss: 0.1292 - val_accuracy: 0.8566 - val_loss: 0.3780


In [39]:
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Accuracy :", accuracy)

782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 31ms/step - accuracy: 0.8523 - loss: 0.3944
Accuracy : 0.8523200154304504


In [40]:
prediction = model.predict(X_test[:5])

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step
[[0.03176393]
 [0.995633  ]
 [0.4544161 ]
 [0.7084114 ]
 [0.9982909 ]]


In [50]:
from tensorflow.keras.datasets import imdb

(X_train, y_train), (X_test, y_test) = imdb.load_data()

word_index = imdb.get_word_index()
word_index

{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

In [41]:
predicted = (prediction > 0.5).astype(int)

print(predicted)

[[0]
 [1]
 [0]
 [1]
 [1]]


In [42]:
import pandas as pd
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [43]:
df = pd.read_csv("spam.csv")

df.head()
print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'spam.csv'

In [ ]:
X = df["message"]

y = df["label"]

In [ ]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(y[:10])

In [ ]:
tokenizer = Tokenizer(
    num_words=5000
)

tokenizer.fit_on_texts(X)

In [ ]:
X = tokenizer.texts_to_sequences(X)

In [ ]:
X = pad_sequences(
    X,
    maxlen=50
)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(

X,

y,

test_size=0.2,

random_state=42

)

In [ ]:
model = Sequential()

In [ ]:
model.add(

Embedding(

input_dim=5000,

output_dim=32

)

)

In [ ]:
model.add(

LSTM(64)

)

In [ ]:
model.add(

Dense(

1,

activation="sigmoid"

)

)

In [ ]:
model.compile(

optimizer="adam",

loss="binary_crossentropy",

metrics=["accuracy"]

)

In [ ]:
model.fit(

X_train,

y_train,

epochs=5,

batch_size=32,

validation_split=0.2

)

In [ ]:
loss,accuracy=model.evaluate(

X_test,

y_test

)

print(accuracy)

In [ ]:
message = [

"Congratulations you won 50000 rupees"

]

In [ ]:
message = tokenizer.texts_to_sequences(message)

message = pad_sequences(

message,

maxlen=50

)

In [ ]:
prediction = model.predict(message)

print(prediction)

In [ ]:
if prediction > 0.5:

    print("Spam")

else:

    print("Ham")

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.read_csv("language.csv")

df.head()

In [ ]:
X = df["Text"]

y = df["Language"]

In [ ]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [ ]:
tokenizer = Tokenizer(num_words=5000)

tokenizer.fit_on_texts(X)

X = tokenizer.texts_to_sequences(X)

In [ ]:
X = pad_sequences(
    X,
    maxlen=20
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = Sequential()

model.add(
    Embedding(
        5000,
        32
    )
)

model.add(
    LSTM(64)
)

model.add(
    Dense(
        len(np.unique(y)),
        activation="softmax"
    )
)

In [ ]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32
)

In [ ]:
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print(accuracy)

In [ ]:
text = ["Bonjour"]

text = tokenizer.texts_to_sequences(text)

text = pad_sequences(
    text,
    maxlen=20
)

In [ ]:
prediction = model.predict(text)

index = np.argmax(prediction)

print(
    encoder.inverse_transform([index])
)

In [51]:
import pandas as pd
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from sklearn.preprocessing import LabelEncoder

In [52]:
questions = [

    "hi",
    "hello",
    "good morning",
    "bye",
    "goodbye",
    "thanks",
    "thank you",
    "what is ai",
    "who are you",
    "how are you"

]

answers = [

    "Hello 😊",
    "Hello 😊",
    "Good Morning 😊",
    "Good Bye 👋",
    "See You Soon 👋",
    "Welcome 😊",
    "Welcome 😊",
    "Artificial Intelligence",
    "I am AI ChatBot",
    "I am Fine 😊"

]

In [53]:
encoder = LabelEncoder()

y = encoder.fit_transform(answers)

print(y)

[3 3 2 1 6 7 7 0 4 5]


In [54]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(questions)

X = tokenizer.texts_to_sequences(questions)

print(X)

[[3], [4], [5, 6], [7], [8], [9], [10, 1], [11, 12, 13], [14, 2, 1], [15, 2, 1]]


In [55]:
max_length = max(len(i) for i in X)

X = pad_sequences(

    X,

    maxlen=max_length,

    padding="post"

)

print(X)

[[ 3  0  0]
 [ 4  0  0]
 [ 5  6  0]
 [ 7  0  0]
 [ 8  0  0]
 [ 9  0  0]
 [10  1  0]
 [11 12 13]
 [14  2  1]
 [15  2  1]]


In [56]:
model = Sequential()
model.add(

    Embedding(

        input_dim=len(tokenizer.word_index)+1,

        output_dim=16

    )

)

model.add(

    LSTM(32)

)

model.add(

    Dense(

        len(np.unique(y)),

        activation="softmax"

    )

)

In [57]:
model.compile(

    optimizer="adam",

    loss="sparse_categorical_crossentropy",

    metrics=["accuracy"]

)

In [58]:
model.fit(

    X,

    y,

    epochs=300

)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.1000 - loss: 2.0798
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 2.0777
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2000 - loss: 2.0756
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.3000 - loss: 2.0736
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.3000 - loss: 2.0715
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3000 - loss: 2.0694
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.3000 - loss: 2.0672
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.3000 - loss: 2.0650
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.3000 - loss: 2.0628
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3000 - loss: 2.0606
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.3000 - loss: 2.0583
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.3000 - 

In [59]:
question = ["hi"]

test = tokenizer.texts_to_sequences(question)

test = pad_sequences(

    test,

    maxlen=max_length,

    padding="post"

)

In [60]:
prediction = model.predict(test)

index = np.argmax(prediction)

print(index)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step
3


In [61]:
answer = encoder.inverse_transform([index])

print(answer[0])

Hello 😊


In [62]:
while True:

    question = input("You : ")

    if question.lower() == "exit":
        break

    test = tokenizer.texts_to_sequences([question])

    test = pad_sequences(
        test,
        maxlen=max_length,
        padding="post"
    )

    prediction = model.predict(test, verbose=0)

    index = np.argmax(prediction)

    answer = encoder.inverse_transform([index])

    print("Bot :", answer[0])

You : hllo
Bot : Hello 😊
You : hi
Bot : Hello 😊
You : how are you
Bot : I am Fine 😊
You : whats up
Bot : Hello 😊
You : my name is
Bot : See You Soon 👋


KeyboardInterrupt: Interrupted by user