In [49]:
import pandas as pd
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [50]:

QUESTIONS=[

"What is Artificial Intelligence?",
"What is Machine Learning?",
"What is Deep Learning?",
"What is Python?",
"Who developed Python?",
"What is TensorFlow?",
"What is Keras?",
"What is NumPy?",
"What is Pandas?",
"What is Matplotlib?",
"What is OpenCV?",
"What is Natural Language Processing?",
"What is a Neural Network?",
"What is a Dataset?",
"What is Training Data?",
"What is Testing Data?",
"What is an Epoch?",
"What is Batch Size?",
"What is Learning Rate?",
"What is Overfitting?",
"What is Underfitting?",
"What is Classification?",
"What is Regression?",
"What is Clustering?",
"What is Data Science?",
"What is SQL?",
"What is JSON?",
"What is an API?",
"What is Git?",
"What is Streamlit?"]

ANSWERS=[

"Artificial Intelligence is the field of creating computer systems that can perform tasks requiring human intelligence.",
"Machine Learning is a branch of AI that enables computers to learn patterns from data.",
"Deep Learning is a subset of Machine Learning that uses neural networks with multiple layers.",
"Python is a high-level programming language known for its simplicity and versatility.",
"Python was developed by Guido van Rossum.",
"TensorFlow is an open-source library used for machine learning and deep learning.",
"Keras is a high-level API for building and training neural network models.",
"NumPy is a Python library used for numerical and mathematical operations.",
"Pandas is a Python library used for data analysis and manipulation.",
" Matplotlib is a Python library used for creating graphs and visualizations.",
"OpenCV is an open-source library used for computer vision and image processing.",
"Natural Language Processing is the field of AI that enables computers to understand and process human language.",
"A Neural Network is a computational model inspired by the human brain for learning patterns.",
"A Dataset is a collection of data used for analysis or model training.",
"Training Data is the data used to teach a machine learning model.",
"Testing Data is the data used to evaluate a trained machine learning model.",
"An Epoch is one complete pass of the training dataset through the model.",
"Batch Size is the number of training samples processed before updating the model.",
"Learning Rate determines how much the model's weights are updated during training.",
"Overfitting occurs when a model learns the training data too well and performs poorly on new data.",
"Underfitting occurs when a model fails to learn the patterns in the training data.",
"Classification is a machine learning task that predicts categories or class labels.",
"Regression is a machine learning task used to predict continuous numerical values.",
"Clustering is an unsupervised learning technique that groups similar data points.",
"Data Science is the process of extracting meaningful insights from data.",
"SQL is a programming language used to manage and query relational databases.",
"JSON is a lightweight format used for storing and exchanging structured data.",
"An API is an Application Programming Interface that allows software applications to communicate with each other.",
"Git is a version control system used to track changes in source code.",
"Streamlit is a Python framework used to build interactive web applications for data science and machine learning."]

In [51]:
encoder = LabelEncoder()

y= encoder.fit_transform(ANSWERS)

y

array([ 5, 15, 10, 21, 22, 26, 13, 17, 20,  0, 18, 16,  2,  1, 28, 27,  4,
        6, 14, 19, 29,  7, 23,  8,  9, 24, 12,  3, 11, 25])

In [53]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(QUESTIONS)

In [54]:
X = tokenizer.texts_to_sequences(QUESTIONS)

In [55]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(QUESTIONS)

X = tokenizer.texts_to_sequences(QUESTIONS)

print(X)

[[1, 2, 8, 9], [1, 2, 10, 3], [1, 2, 11, 3], [1, 2, 5], [12, 13, 5], [1, 2, 14], [1, 2, 15], [1, 2, 16], [1, 2, 17], [1, 2, 18], [1, 2, 19], [1, 2, 20, 21, 22], [1, 2, 6, 23, 24], [1, 2, 6, 25], [1, 2, 26, 4], [1, 2, 27, 4], [1, 2, 7, 28], [1, 2, 29, 30], [1, 2, 3, 31], [1, 2, 32], [1, 2, 33], [1, 2, 34], [1, 2, 35], [1, 2, 36], [1, 2, 4, 37], [1, 2, 38], [1, 2, 39], [1, 2, 7, 40], [1, 2, 41], [1, 2, 42]]


In [56]:
max_length = max(len(i) for i in X)

X = pad_sequences(

    X,

    maxlen=max_length,

    padding="post"

)

print(X)

[[ 1  2  8  9  0]
 [ 1  2 10  3  0]
 [ 1  2 11  3  0]
 [ 1  2  5  0  0]
 [12 13  5  0  0]
 [ 1  2 14  0  0]
 [ 1  2 15  0  0]
 [ 1  2 16  0  0]
 [ 1  2 17  0  0]
 [ 1  2 18  0  0]
 [ 1  2 19  0  0]
 [ 1  2 20 21 22]
 [ 1  2  6 23 24]
 [ 1  2  6 25  0]
 [ 1  2 26  4  0]
 [ 1  2 27  4  0]
 [ 1  2  7 28  0]
 [ 1  2 29 30  0]
 [ 1  2  3 31  0]
 [ 1  2 32  0  0]
 [ 1  2 33  0  0]
 [ 1  2 34  0  0]
 [ 1  2 35  0  0]
 [ 1  2 36  0  0]
 [ 1  2  4 37  0]
 [ 1  2 38  0  0]
 [ 1  2 39  0  0]
 [ 1  2  7 40  0]
 [ 1  2 41  0  0]
 [ 1  2 42  0  0]]


In [62]:
model = Sequential()
model.add(

    Embedding(

        input_dim=len(tokenizer.word_index)+1,

        output_dim=16

    )

)

model.add(

    LSTM(64)

)

model.add(

    Dense(

        len(np.unique(y)),

        activation="softmax"

    )

)

In [63]:
model.compile(

    optimizer="adam",

    loss="sparse_categorical_crossentropy",

    metrics=["accuracy"]

)

In [64]:
model.fit(

    X,

    y,

    epochs=300

)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0333 - loss: 3.4008
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0333 - loss: 3.4001
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1000 - loss: 3.3994
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.1333 - loss: 3.3987
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1333 - loss: 3.3979
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1333 - loss: 3.3972
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1667 - loss: 3.3965
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.2000 - loss: 3.3957
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.2333 - loss: 3.3949
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3000 - loss: 3.3940
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3000 - loss: 3.3931
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3333 - loss

In [60]:
# question = ["4. What is Python?"]

# test = tokenizer.texts_to_sequences(question)

# test = pad_sequences(

#     test,

#     maxlen=max_length,

#     padding="post"

# )

In [46]:
# prediction = model.predict(test)

# index = np.argmax(prediction)

# print(index)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
27


In [65]:
ANSWERS = encoder.inverse_transform([index])

print(ANSWERS[0])

Deep Learning is a subset of Machine Learning that uses neural networks with multiple layers.


In [68]:
while True:

    QUESTIONS = input("You : ")

    if QUESTIONS.lower() == "exit":
        break

    test = tokenizer.texts_to_sequences([QUESTIONS])

    test = pad_sequences(
        test,
        maxlen=max_length,
        padding="post"
    )

    prediction = model.predict(test, verbose=0)

    index = np.argmax(prediction)

    answer = encoder.inverse_transform([index])

    print("Bot :", answer[0])

You : What is Git?
Bot : Git is a version control system used to track changes in source code.
You : What is Streamlit?
Bot : Streamlit is a Python framework used to build interactive web applications for data science and machine learning.
You : What is Deep Learning?
Bot : Deep Learning is a subset of Machine Learning that uses neural networks with multiple layers.
You : What is Artificial Intelligence?
Bot : Artificial Intelligence is the field of creating computer systems that can perform tasks requiring human intelligence.
You : exit
