In [3]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical



data = """
I am going to school
I am going to market
I am playing cricket
I love machine learning
Machine learning is amazing
Deep learning is powerful
Deep learning uses neural networks
Python is easy
Python is popular
Artificial intelligence is the future
"""


tokenizer = Tokenizer()

tokenizer.fit_on_texts([data])


print(tokenizer.word_index)

{'is': 1, 'i': 2, 'learning': 3, 'am': 4, 'going': 5, 'to': 6, 'machine': 7, 'deep': 8, 'python': 9, 'school': 10, 'market': 11, 'playing': 12, 'cricket': 13, 'love': 14, 'amazing': 15, 'powerful': 16, 'uses': 17, 'neural': 18, 'networks': 19, 'easy': 20, 'popular': 21, 'artificial': 22, 'intelligence': 23, 'the': 24, 'future': 25}


In [6]:
input_sequences = []

for line in data.split("\n"):

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):

        n_gram = token_list[:i+1]

        input_sequences.append(n_gram)

print(input_sequences)

[[2, 4], [2, 4, 5], [2, 4, 5, 6], [2, 4, 5, 6, 10], [2, 4], [2, 4, 5], [2, 4, 5, 6], [2, 4, 5, 6, 11], [2, 4], [2, 4, 12], [2, 4, 12, 13], [2, 14], [2, 14, 7], [2, 14, 7, 3], [7, 3], [7, 3, 1], [7, 3, 1, 15], [8, 3], [8, 3, 1], [8, 3, 1, 16], [8, 3], [8, 3, 17], [8, 3, 17, 18], [8, 3, 17, 18, 19], [9, 1], [9, 1, 20], [9, 1], [9, 1, 21], [22, 23], [22, 23, 1], [22, 23, 1, 24], [22, 23, 1, 24, 25]]


In [7]:
max_len = max(len(seq) for seq in input_sequences)

In [9]:
input_sequences = pad_sequences(
    input_sequences,
    maxlen=max_len,
    padding='pre'
)

print(input_sequences)

[[ 0  0  0  2  4]
 [ 0  0  2  4  5]
 [ 0  2  4  5  6]
 [ 2  4  5  6 10]
 [ 0  0  0  2  4]
 [ 0  0  2  4  5]
 [ 0  2  4  5  6]
 [ 2  4  5  6 11]
 [ 0  0  0  2  4]
 [ 0  0  2  4 12]
 [ 0  2  4 12 13]
 [ 0  0  0  2 14]
 [ 0  0  2 14  7]
 [ 0  2 14  7  3]
 [ 0  0  0  7  3]
 [ 0  0  7  3  1]
 [ 0  7  3  1 15]
 [ 0  0  0  8  3]
 [ 0  0  8  3  1]
 [ 0  8  3  1 16]
 [ 0  0  0  8  3]
 [ 0  0  8  3 17]
 [ 0  8  3 17 18]
 [ 8  3 17 18 19]
 [ 0  0  0  9  1]
 [ 0  0  9  1 20]
 [ 0  0  0  9  1]
 [ 0  0  9  1 21]
 [ 0  0  0 22 23]
 [ 0  0 22 23  1]
 [ 0 22 23  1 24]
 [22 23  1 24 25]]


In [10]:
X = input_sequences[:, :-1]

y = input_sequences[:, -1]

In [11]:
print(X.shape)

print(y.shape)

(32, 4)
(32,)


In [12]:
total_words = len(tokenizer.word_index)+1

In [13]:
y = to_categorical(
    y,
    num_classes=total_words
)

In [14]:
model = Sequential()

model.add(
    Embedding(
        total_words,
        100,
        input_length=max_len-1
    )
)

model.add(
    LSTM(150)
)

model.add(
    Dense(
        total_words,
        activation="softmax"
    )
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [16]:
history = model.fit(
    X,
    y,
    epochs=300,
    verbose=1
)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.0625 - loss: 3.2585
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1250 - loss: 3.2486
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1875 - loss: 3.2385
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1875 - loss: 3.2281
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.1875 - loss: 3.2169
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1875 - loss: 3.2046
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1875 - loss: 3.1908
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.1875 - loss: 3.1751
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1875 - loss: 3.1569
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1875 - loss: 3.1359
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.1875 - loss: 3.1112
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1562 - loss

In [17]:
def predict_next_word(text):

    token_list = tokenizer.texts_to_sequences([text])[0]

    token_list = pad_sequences(
        [token_list],
        maxlen=max_len-1,
        padding='pre'
    )

    predicted = np.argmax(model.predict(token_list, verbose=0))

    for word, index in tokenizer.word_index.items():

        if index == predicted:

            return word

In [19]:
print(predict_next_word("I am going to"))

school


In [20]:
print(predict_next_word("Deep learning"))

is


In [21]:
print(predict_next_word("Python is"))

popular
