In [ ]:
import numpy as np

X = np.array([
    [1, 0, 1, 0],   # I
    [0, 2, 0, 2],   # love
    [1, 1, 1, 1]    # AI
])

print(X)
print("Shape :", X.shape)

[[1 0 1 0]
 [0 2 0 2]
 [1 1 1 1]]
Shape : (3, 4)


In [ ]:
WQ = np.array([
    [1,0],
    [0,1],
    [1,0],
    [0,1]
])

WK = np.array([
    [0,1],
    [1,0],
    [0,1],
    [1,0]
])

WV = np.array([
    [1,1],
    [0,1],
    [1,0],
    [0,1]
])

print(WQ.shape)
print(WK.shape)
print(WV.shape)

(4, 2)
(4, 2)
(4, 2)


In [ ]:
import numpy as np

X = np.array([
    [1,0,1,0],
    [0,2,0,2],
    [1,1,1,1]
])

WQ = np.array([
    [1,0],
    [0,1],
    [1,0],
    [0,1]
])

print("X Shape :", X.shape)
print("WQ Shape :", WQ.shape)

Q = X @ WQ

print(Q)
print("Q Shape :", Q.shape)

X Shape : (3, 4)
WQ Shape : (4, 2)
[[2 0]
 [0 4]
 [2 2]]
Q Shape : (3, 2)


In [ ]:
Q = X @ WQ
K = X @ WK
V = X @ WV

print("Query")
print(Q)

print("\nKey")
print(K)

print("\nValue")
print(V)

Query
[[2 0]
 [0 4]
 [2 2]]

Key
[[0 2]
 [4 0]
 [2 2]]

Value
[[2 1]
 [0 4]
 [2 3]]


In [ ]:
scores = Q @ K.T

print(scores)
print(scores.shape)


[[0 8 4]
 [8 0 8]
 [4 8 8]]
(3, 3)


In [ ]:
dk = K.shape[1]

scores = scores / np.sqrt(dk)

print(scores)

[[0.         5.65685425 2.82842712]
 [5.65685425 0.         5.65685425]
 [2.82842712 5.65685425 5.65685425]]


In [ ]:
def softmax(x):

    exp = np.exp(x - np.max(x, axis=-1, keepdims=True))

    return exp / np.sum(exp, axis=-1, keepdims=True)

In [ ]:
weights = softmax(scores)

print(weights)

[[0.00328768 0.94108857 0.05562374]
 [0.49912815 0.0017437  0.49912815]
 [0.02870457 0.48564771 0.48564771]]


In [ ]:
output = weights @ V

print(output)
print(output.shape)





# i love india,python is easy to learn

# easy to

[[0.11782285 3.93451321]
 [1.9965126  2.0034874 ]
 [1.02870457 3.42823857]]
(3, 2)
