# CNN Module 1 - Image Fundamentals (Detailed)

Detailed notes on images, pixels, grayscale and RGB images.

## What is an Image?

Humans see objects. Computers see numbers.

Every image is stored as numerical pixel values.


## Pixels

Pixel = Picture Element

Smallest unit of an image.

Example:
1920 × 1080 = 2,073,600 pixels


## Grayscale Images

Single channel image.

0 = Black
255 = White

Shape:
(height, width)


In [1]:
import numpy as np

img = np.array([
    [0,50,100],
    [150,200,255],
    [30,120,220]
])

print(img)
print(img.shape)


[[  0  50 100]
 [150 200 255]
 [ 30 120 220]]
(3, 3)


## RGB Images

Shape:

(height, width, 3)

Channels:
- Red
- Green
- Blue

Examples:
[255,0,0] = Red
[0,255,0] = Green
[0,0,255] = Blue


## Why Resize Images?

Benefits:
- Faster training
- Less memory
- Lower computation


## Interview Questions

1. What is a pixel?
2. What is a grayscale image?
3. What is an RGB image?
4. What is image shape?
5. Why resize images?
