In [1]:
# STEP 1: Import Libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

In [3]:
# STEP 2: Load Dataset

df = pd.read_csv("Logistic-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2


In [4]:
# STEP 3: Convert Target Variable

df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [6]:
# STEP 4: Drop Useless Columns (VERY IMPORTANT)

df = df.drop(['EmployeeCount', 'EmployeeNumber', 'Over18','StandardHours'], axis = 1)

# 👉 These are constant / useless → remove

In [7]:
# STEP 5: Handle Categorical Variables

df = pd.get_dummies(df, drop_first=True)


# 👉 Converts:

# Gender
# JobRole
# Department
# etc.

In [8]:
# STEP 6: Define Features & Target

X = df.drop("Attrition", axis = 1)

y = df['Attrition']

In [9]:
# STEP 7: Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [10]:
# STEP 8: Feature Scaling

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
# STEP 9: Train Logistic Regression Model

model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [14]:
# STEP 10: MODEL PREDICTION (MAIN PART)

# Class Prediction

y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [15]:
# Probability Prediction

y_prob = model.predict_proba(X_test)[:,1]
y_prob

# 👉 Example:

# 0.78 → 78% chance employee will leave

array([6.46772681e-02, 2.65000732e-03, 3.41192320e-01, 1.30210238e-02,
       5.08455342e-02, 3.26139609e-01, 4.03090336e-01, 3.46400090e-02,
       6.10758723e-02, 1.37828292e-02, 5.15996901e-01, 5.29804006e-02,
       8.16176587e-02, 3.82725549e-02, 2.33820071e-02, 1.02965040e-01,
       1.73481824e-01, 1.14534709e-01, 1.77541802e-01, 2.97000391e-02,
       5.56443057e-01, 2.58148164e-03, 4.38842346e-02, 3.86234107e-01,
       1.21122698e-01, 2.29084540e-02, 7.36184304e-02, 7.29054208e-03,
       8.32292398e-02, 2.99081448e-02, 7.70889498e-03, 2.01472078e-03,
       1.64099120e-03, 2.54143491e-02, 5.28527359e-01, 3.79041363e-03,
       2.46707851e-04, 2.07524817e-01, 8.58855926e-01, 1.70894943e-02,
       4.95997936e-02, 1.07332743e-01, 4.29239211e-02, 4.64650194e-02,
       7.22544870e-01, 6.49138535e-03, 8.23265214e-01, 5.44035707e-01,
       5.22401334e-01, 4.87400624e-01, 5.79099392e-03, 1.60314393e-01,
       5.03458558e-03, 7.77803728e-02, 1.19843034e-01, 9.58465744e-02,
      

In [16]:
# STEP 11: Model Evaluation

# Accuracy

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8809523809523809


In [21]:
# Confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[241  14]
 [ 21  18]]


In [22]:
# Classification Report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93       255
           1       0.56      0.46      0.51        39

    accuracy                           0.88       294
   macro avg       0.74      0.70      0.72       294
weighted avg       0.87      0.88      0.88       294



In [23]:
# AUC Score (IMPORTANT)

print("AUC:", roc_auc_score(y_test, y_prob))

AUC: 0.7903469079939668


In [24]:
# STEP 12: Predict NEW EMPLOYEE

sample = X_test[0].reshape(1, -1)

pred = model.predict(sample)
prob = model.predict_proba(sample)

print("Attrition Prediction:", pred)
print("Probability:", prob)

Attrition Prediction: [0]
Probability: [[0.93532273 0.06467727]]
