In [ ]:
### import numpy as np

# arr=np.array([1,2,3,4])
# print(arr)
# print(arr.ndim) #ndim : Dimension 
# print(arr.shape) #shape : returns a tuple of integers


# arr2d=np.array([[1,2,3,4],
#                 [5,6,7,8]])
# print(arr2d.shape)


# arr3d=np.array([[[1,2,3,4]]])

# print(arr3d.shape)



building=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(building.shape)
print(building.ndim)


# arr3d=np.array([[[1,2,3],
#                  [4,5,6],
#                  [7,8,9]],
                
#                 [[10,11,12],
#                  [13,14,21],
#                  [101,23,25]]])
# print(arr3d.shape)


# arr10d=np.array([10,20,30,40],ndmin=10)
# print(arr10d.ndim)




Practice Questions:-


Q-1: Create a 1D array with values [5,10,15,20,25].

->Print the array.

->Print its dimension and shape.


Q-2: Create a 1D array of numbers from 0 to 9.

->Verify that its 1D.

->Print its shape.


Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.

->Print the array.

->Print its ndim and shape.


Q-4: Create a 2D array (3*3) filled with numbers 1 to 9.

->Print the array.

->Verify its Dimension and Shape.


Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.

->Print the array.

->Print its shape and dimensions.

Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).

->Print the array.

->Print its dimension and shape.

Q-7 Create 4D array with shape(1,2,2,3).

->Print the array.

->Print its shape and dimensions.



In [2]:
# Q-1: Create a 1D array with values [5,10,15,20,25].
# ->Print the array.
# ->Print its dimension and shape.

import numpy as np
arr = np.array([5,10,15,20,25])
print(arr)
print(arr.ndim)
print(arr.shape)

[ 5 10 15 20 25]
1
(5,)


In [9]:
# Q-2: Create a 1D array of numbers from 0 to 9.
# ->Verify that its 1D.
# ->Print its shape.

arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr.ndim)
print(arr.shape)

1
(10,)


In [18]:
# Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.
# ->Print the array.
# ->Print its ndim and shape.

arr2D = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2D)
print(arr2D.ndim)
print(arr2D.shape)

[[1 2 3 4]
 [4 5 6 7]]
2
(2, 4)


In [21]:
# Q-4: Create a 2D array (3*3) filled with numbers 1 to 9.
# ->Print the array.
# ->Verify its Dimension and Shape.

arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2D)
print(arr2D.ndim)
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [24]:
# Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.
# ->Print the array.
# ->Print its shape and dimensions.

arr3D = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
(2, 3, 2)
3


In [39]:
# Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).
# ->Print the array.
# ->Print its dimension and shape.

arr3D = np.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
(2, 2, 3)
3


In [43]:
# Q-7 Create 4D array with shape(1,2,2,3).
# ->Print the array.
# ->Print its shape and dimensions.

arr4D = np.array([[
    [[1,2,3],[4,5,6]],
    [[7,8,9],[9,10,11]]
]])
print(arr4D)
print(arr4D.shape)
print(arr4D.ndim)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [ 9 10 11]]]]
(1, 2, 2, 3)
4


In [45]:
ar = np.array([[[[123,456,456]]]])
print(ar.ndim)
print(ar.shape)

4
(1, 1, 1, 3)


# Level 1 — Basics (ndim + shape)
Task 1

Create a NumPy array:

[5, 10, 15, 20, 25]

Print:

• ndim • shape

Task 2

Create a 2D array:

[[1,2,3], [4,5,6]]

Print:

• ndim • shape

Task 3

Create a 3D array like this:

[ [[1,2],[3,4]], [[5,6],[7,8]] ]

Print:

• ndim • shape

In [46]:
# Task 1
# Create a NumPy array:
# [5, 10, 15, 20, 25]
# Print:
# • ndim • shape

arr = np.array([5,10,15,20,25])
print(arr.ndim)
print(arr.shape)

1
(5,)


In [48]:
# Task 2
# Create a 2D array:
# [[1,2,3], [4,5,6]]
# Print:
# • ndim • shape

arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D.ndim)
print(arr2D.shape)

2
(2, 3)


In [55]:
# Task 3
# Create a 3D array like this:
# [ [[1,2],[3,4]], [[5,6],[7,8]] ]
# Print:
# • ndim • shape

arr3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


# Level 2 — Think in Dimensions 

Task 4

Create an array using ndmin=5 with values:

[10,20,30]

Check:

print(arr.ndim) print(arr.shape)

Task 5

Predict BEFORE running:

a = np.array([[1,2,3,4]]) print(a.shape)

Write answer first → then run.

Task 6

Create this:

[ [ [1,2,3] ], [ [4,5,6] ] ]

Then print:

• ndim • shape

In [57]:
# Task 4
# Create an array using ndmin=5 with values:
# [10,20,30]
# Check:
# print(arr.ndim) print(arr.shape)

# arr10d=np.array([10,20,30,40],ndmin=10)

arr = np.array([10,20,30], ndmin=5)
print(arr.ndim)
print(arr.shape)

5
(1, 1, 1, 1, 3)


In [59]:
# Task 5
# Predict BEFORE running:
# a = np.array([[1,2,3,4]]) print(a.shape)
# Write answer first → then run.

a = np.array([[1,2,3,4]])
print(a.shape)
print(a.ndim)

(1, 4)
2


In [62]:
# Task 6
# Create this:
# [ [ [1,2,3] ], [ [4,5,6] ] ]
# Then print:
# • ndim • shape

arr = np.array([ [ [1,2,3] ], [ [4,5,6] ] ])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2 3]]

 [[4 5 6]]]
3
(2, 1, 3)


# Level 3 — Real World Style Shapes 
Task 7 (Building Problem)

Create:

3 buildings
2 floors each
4 rooms per floor

Fill with random numbers.

Print shape.

(Hint: (3,2,4))

✅ Task 8

Create student marks:

2 classes
3 students
5 subjects

Print shape.

Task:-

Create:

5 samples
3 rows
2 columns

Then answer:

• ndim • shape • total elements

In [68]:
# Task 7 (Building Problem)
# Create:
# 3 buildings 2 floors each 4 rooms per floor
# Fill with random numbers.
# Print shape.
# (Hint: (3,2,4))
 
import numpy as np 

building = np.array([[[1,2,3,4],[5,6,7,8]],[[11,12,13,14,],[15,16,17,18]],[[21,22,23,24],[25,26,27,28]]])
print(building)
print(building.shape)
print(building.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]

 [[21 22 23 24]
  [25 26 27 28]]]
(3, 2, 4)
3


In [73]:
# Task 8
# Create student marks:
# 2 classes 3 students 5 subjects
# Print shape.


classes = np.array([[[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25]],[[31,32,33,34,35],[41,42,43,44,45],[51,52,53,54,55]]]) 
print(classes)
print(classes.ndim)
print(classes.shape)


[[[ 1  2  3  4  5]
  [11 12 13 14 15]
  [21 22 23 24 25]]

 [[31 32 33 34 35]
  [41 42 43 44 45]
  [51 52 53 54 55]]]
3
(2, 3, 5)


In [77]:
# Task 9
# Create:
# 5 samples 3 rows 2 columns
# Then answer:
# • ndim • shape • total elements

arr = np.array([[[1,2],[3,4],[5,6]],
                [[7,8],[9,10],[11,12]],
                [[13,14],[15,16],[17,18]],
                [[19,20],[21,22],[23,24]],
                [[25,26],[27,28],[29,30]]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]]]
3
(5, 3, 2)
30
