In [25]:
import numpy as np

In [26]:
# 1. Generate 6 random float numbers between 0 and 1 using np.random.rand().

arr = np.random.rand(6)
print(arr)

[0.44583275 0.09997492 0.45924889 0.33370861 0.14286682 0.65088847]


In [27]:
# 2. Create a 2×5 random float matrix using np.random.rand().

matrix = np.random.rand(2, 5)
print(matrix)

[[5.64115790e-02 7.21998772e-01 9.38552709e-01 7.78765841e-04
  9.92211559e-01]
 [6.17481510e-01 6.11653160e-01 7.06630522e-03 2.30624250e-02
  5.24774660e-01]]


In [28]:
# 3. Generate 8 random integers between 10 and 20 using np.random.randint().

arr = np.random.randint(10, 20, 8)
print(arr)

[19 12 16 13 18 12 14 12]


In [29]:
# 4. Create a 3×3 matrix of random integers between 1 and 9.

matrix = np.random.randint(1, 10, (3, 3))
print(matrix)

[[7 5 9]
 [7 2 4]
 [9 2 9]]


In [31]:
# 5. Generate 5 random numbers from standard normal distribution using
# np.random.randn().

arr = np.random.randn(5)
print(arr)

[-1.15877024  0.56611283 -0.70445345 -1.3779393  -0.35311665]


In [34]:
# 6. Create a random array of shape (4, 3, 2) using np.random.rand() and:
# o print its shape
# o print its ndim

arr = np.random.rand(4, 3, 2)

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)

Array:
 [[[0.71066289 0.11089082]
  [0.4393365  0.2017192 ]
  [0.8957636  0.47537022]]

 [[0.56327557 0.69551609]
  [0.13933145 0.60441738]
  [0.53984109 0.20306122]]

 [[0.94285357 0.59886547]
  [0.69478493 0.88046784]
  [0.62435405 0.29563369]]

 [[0.10549426 0.45653457]
  [0.21844044 0.41650995]
  [0.88328026 0.32434502]]]
Shape: (4, 3, 2)
Number of dimensions: 3


In [8]:
# 7. Generate a 1D random integer array of size 15 and find:
# o maximum value
# o minimum value
# o mean value

arr = np.random.randint(1, 100, 15)

print("Array:", arr)

print("Maximum value:", arr.max())
print("Minimum value:", arr.min())
print("Mean value:", arr.mean())


Array: [67 53 44 46 85 13 26 24 84 37 61 65 53  3 27]
Maximum value: 85
Minimum value: 3
Mean value: 45.86666666666667


In [37]:
# 8. Create a random 2D integer array (4×4) and check:
# o number of rows
# o number of columns
# o total elements

arr = np.random.randint(1, 50, (4, 4))

print("Array:\n", arr)

print("Number of rows:", arr.shape[0])
print("Number of columns:", arr.shape[1])
print("Total elements:", arr.size)

Array:
 [[ 2 28 23 37]
 [32 33  1 19]
 [ 2 44 26 32]
 [ 6 32  4 11]]
Number of rows: 4
Number of columns: 4
Total elements: 16


In [38]:
# 9. arr = np.array([10, 20, 30, 40, 50])
# Pick 3 random elements using np.random.choice().

arr = np.array([10, 20, 30, 40, 50])

random_elements = np.random.choice(arr, 3)

print("Selected elements:", random_elements)


Selected elements: [30 10 50]


In [41]:
# 10. From the same array, pick 4 elements with repetition.

arr = np.array([10, 20, 30, 40, 50])

picked = np.random.choice(arr, 4, replace=True)
print(picked)

[30 40 40 30]


In [43]:
# 11. Shuffle this array using np.random.shuffle():
# arr = np.array([1, 2, 3, 4, 5, 6])

arr = np.array([1, 2, 3, 4, 5, 6])

np.random.shuffle(arr)

print(arr)

[1 2 6 5 4 3]


In [46]:
# 12. Use np.random.seed(10) and generate 5 random integers (1–50).
# Run the code twice and verify the output is the same.

np.random.seed(10)
arr = np.random.randint(1, 51, 5)

print(arr)

[10 37 16  1 50]


In [50]:
# 13. Student Marks
#  Generate marks for 12 students (0–100)
#  Find:
# o highest mark
# o lowest mark
# o average mark
#  Randomly select 3 students for a prize


marks = np.random.randint(0, 101, 12)
print("Student Marks:", marks)



print("Highest mark:", marks.max())
print("Lowest mark:", marks.min())
print("Average mark:", marks.mean())



selected_students = np.random.choice(len(marks), 3, replace=False)

print("Selected student index for prize:", selected_students)
print("Their marks:", marks[selected_students])

Student Marks: [54 34 15 77 88 15  6 85 22 11 12 92]
Highest mark: 92
Lowest mark: 6
Average mark: 42.583333333333336
Selected student index for prize: [ 5 10  3]
Their marks: [15 12 77]


In [53]:
# 14. Weekly Sales
#  Generate sales for 7 days (200–1000)
#  Find:
# o highest sales day
# o lowest sales day
#  Shuffle the sales data

sales = np.random.randint(200, 1001, 7)
print("Weekly Sales:", sales)



highest_day = np.argmax(sales)
lowest_day = np.argmin(sales)
print("Highest sales:", sales[highest_day], "on day index:", highest_day)
print("Lowest sales:", sales[lowest_day], "on day index:", lowest_day)



np.random.shuffle(sales)
print("Shuffled Sales:", sales)

Weekly Sales: [290 468 698 486 409 601 344]
Highest sales: 698 on day index: 2
Lowest sales: 290 on day index: 0
Shuffled Sales: [409 698 486 344 468 601 290]


In [55]:
# 15. Dice Game
#  Simulate rolling a dice 20 times
#  Count how many times 6 appear

dice_rolls = np.random.randint(1, 7, 20)
print("Dice Rolls:", dice_rolls)


count_six = np.sum(dice_rolls == 6)
print("Number of times 6 appeared:", count_six)


Dice Rolls: [4 1 1 6 2 1 6 4 4 3 1 6 1 5 6 4 2 2 2 6]
Number of times 6 appeared: 5


In [18]:
# 16. Generate a 5×5 random integer matrix (10–99) and find:
#  max value
#  min value
#  mean of all elements


matrix = np.random.randint(10, 100, (5, 5))

print("Matrix:\n", matrix)


print("Maximum value:", matrix.max())
print("Minimum value:", matrix.min())
print("Mean of all elements:", matrix.mean())

Matrix:
 [[98 54 15 14 81]
 [98 98 60 64 44]
 [25 87 98 25 16]
 [95 32 21 22 72]
 [67 89 52 67 60]]
Maximum value: 98
Minimum value: 14
Mean of all elements: 58.16


In [56]:
# 17. Create random salaries for 8 employees (30,000–80,000) and:
#  find lowest salary
#  randomly pick 2 employees for bonus


salaries = np.random.randint(30000, 80001, 8)

print("Employee Salaries:", salaries)

print("Lowest Salary:", salaries.min())



selected_indices = np.random.choice(len(salaries), 2, replace=False)

print("Selected Employee Indices:", selected_indices)
print("Their Salaries:", salaries[selected_indices])


Employee Salaries: [50414 51517 48948 36871 36684 71511 34443 67641]
Lowest Salary: 34443
Selected Employee Indices: [4 2]
Their Salaries: [36684 48948]


In [59]:
# 18. Create an array of 100 random integers and:
#  find how many are greater than 50

arr = np.random.randint(0, 101, 100)
print("Array:\n", arr)


count = np.sum(arr > 50)
print("Count of numbers greater than 50:", count)

Array:
 [94 84 20 49 33  2 97 97 98 12 82 77 66 37 31 56 81 87 81 55 97 74 15 79
 80 38 55 49 90  2 70 97  5 72 29 19 25 15 54 99 96 82 56 41 90 26 74  8
 92 32 71 87 68 86 14 35 84 37 62 67 14 37 57 78 34 51 50 50 85 14 52 30
 81 10 61 23  1 28 58 10 11  1 82 34 11 46 74 36  6 63 60  3 50 59 34 21
 16 18 61 54]
Count of numbers greater than 50: 52


In [61]:
# 19. What is the difference between:
#  np.random.rand()
#  np.random.randn()

result1 = np.random.rand(5)
result2 = np.random.randn(5)

print(result1)   #Range: [0, 1)
print(result2)   #Range: (-∞ to +∞)

[0.02042997 0.80085181 0.2079271  0.14325251 0.69989398]
[-0.53123786  0.19293598  0.00402491 -0.16407529 -1.14881226]


In [24]:
# 20. Why do we use np.random.seed()?


# np.random.seed() is used to make random number generation reproducible.

# Without a seed → different output every run.
# With a seed → same output every run.



# Example Without Seed

print(np.random.randint(1, 10, 5))


# Example With Seed

np.random.seed(42)
print(np.random.randint(1, 10, 5))


[2 2 6 6 1]
[7 4 8 5 7]
