In [1]:
import numpy as np

In [13]:
# 1. Create a NumPy array of 10 numbers and find:
# o mean
# o sum

arr = np.array([5, 12, 8, 20, 15, 7, 9, 14, 3, 11])

print("Array:", arr)

print("Sum:", arr.sum())
print("Mean:", arr.mean())

Array: [ 5 12  8 20 15  7  9 14  3 11]
Sum: 104
Mean: 10.4


In [14]:
# 2. Given an array:
# arr = np.array([5, 10, 15, 20, 25])
# Find:
# o minimum
# o maximum

arr = np.array([5, 10, 15, 20, 25])

print("Minimum:", arr.min())
print("Maximum:", arr.max())


Minimum: 5
Maximum: 25


In [15]:
# 4. Find the average of all elements in a NumPy array.

arr = np.array([12, 25, 18, 40, 30])

average = arr.mean()

print("Average:", average)


Average: 25.0


In [16]:
# 5. Create a NumPy array and calculate:
# o mean
# o median

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)

print("Mean:", arr.mean())
print("Median:", np.median(arr))


Array: [10 20 30 40 50]
Mean: 30.0
Median: 30.0


In [21]:
# 6. Find the standard deviation of an array.

arr = np.array([10, 20, 30, 40, 50])

print("Standard Deviation:",arr.std())


Standard Deviation: 14.142135623730951


In [23]:
# 7. Calculate the variance of a dataset.

import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Variance:", data.var())


Variance: 200.0


In [26]:
# 9. Create a 2D NumPy array (3×4) and find:
# o overall mean

arr = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [12, 22, 32, 42]
])

print("Array:\n", arr)

print("Overall Mean:",arr.mean())


Array:
 [[10 20 30 40]
 [15 25 35 45]
 [12 22 32 42]]
Overall Mean: 27.333333333333332


In [29]:
# 10. Find row-wise mean of a 2D array.

arr = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [12, 22, 32, 42]
])

print("Array:\n", arr)

# Row-wise mean
row_mean = arr.mean(axis=1)

print("Row-wise Mean:", row_mean)


Array:
 [[10 20 30 40]
 [15 25 35 45]
 [12 22 32 42]]
Row-wise Mean: [25. 30. 27.]


In [30]:
# 11. Find column-wise mean of a 2D array.

arr = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [12, 22, 32, 42]
])

print("Array:\n", arr)

# Column-wise mean
col_mean = arr.mean(axis=0)

print("Column-wise Mean:", col_mean)


Array:
 [[10 20 30 40]
 [15 25 35 45]
 [12 22 32 42]]
Column-wise Mean: [12.33333333 22.33333333 32.33333333 42.33333333]


In [31]:
# 12. Find:
#  max value of each row
#  min value of each column

arr = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [12, 22, 32, 42]
])

print("Array:\n", arr)

# Max value of each row
row_max = arr.max(axis=1)

# Min value of each column
col_min = arr.min(axis=0)

print("Max value of each row:", row_max)
print("Min value of each column:", col_min)


Array:
 [[10 20 30 40]
 [15 25 35 45]
 [12 22 32 42]]
Max value of each row: [40 45 42]
Min value of each column: [10 20 30 40]
