# Numpy Introduction


What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
import numpy as np

# arr =np.array(12,ndmin=5)
# print(type(arr))
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)

(2, 2, 3)


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr.shape)

arr0 = np.array(12,ndmin=3)
print(arr0.shape)


(6,)
(1, 1, 1)


In [7]:
import numpy as np

arr = np.array([[[1,2,3,4],[5,6,7,8]]],ndmin=5)

arr0 = np.array(12)

print(type(arr))
print(arr.shape)


<class 'numpy.ndarray'>
(1, 1, 1, 2, 4)


In [8]:
import numpy as np 

arr = np.array([[1,2,3,4],[4,5,6,7]],ndmin=5)

print(type(arr))
print(arr.shape)
print(arr.ndim)


<class 'numpy.ndarray'>
(1, 1, 1, 2, 4)
5


In [9]:
import numpy as np 

arr = np.array([[[1,2,3,4,5,6]]],ndmin=5)
arr0 = np.array(12)

print(arr.shape)
print(arr.ndim)

(1, 1, 1, 1, 6)
5


In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5,6,7]])
print(type(arr))
print(arr.shape)




<class 'numpy.ndarray'>
(1, 7)


In [11]:
arr0 = np.array(21)
print(arr0.ndim)
arr1 = np.array([21])
print(arr1.ndim)
arr2 = np.array([[[[21,34],[2,4],[6,7]]]])
print(arr2.ndim)
print(arr2.shape)

0
1
4
(1, 1, 3, 2)


In [12]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]])


print(arr[1,2])
print(arr.ndim)
print(arr.shape)

4
2
(2, 6)


In [13]:
import numpy as np

In [14]:
(2,4,2)

arr=np.arange(16).reshape(4,4)

# arr=np.arange(16).reshape(4,-1)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [42]:
arr=np.ones((2,3,2))
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [22]:

arr=np.full((2,4),9)
print(arr)

[[9 9 9 9]
 [9 9 9 9]]


In [27]:
arr=np.linspace(0,1,100)
print(arr)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [28]:
arr=np.array([0,1,2,0,4,],dtype='bool')
print(arr)

[False  True  True False  True]


In [ ]:
# (2,3,2)

import numpy as np

arr2d=np.array([[1,2,3],
                [4,5,6]])


print(arr2d)

arr3d=np.array([[[1,2],[3,4],[5,6]],
                [[7,8],[9,10],[11,12]]])

print(arr3d.ndim)


print(arr3d)


arr=np.zeros((2,3,2))
print(arr)

arr1=np.ones((3,4))
print(arr1)

arr=np.full((2,4),9)
print(arr)


arr=np.arange(1,10,2)
print(arr)

arr=np.arange(11)
print(arr)

arr=np.linspace(0,1,100)
print(arr)

arr=np.array([[1,2,3],[4,5,6]])

print(np.ones_like(arr))


arr=np.array([0,1,2,0,4,],dtype='bool')
print(arr)

 
arr=np.array([1,2,3,4,5])


# astype

converted=arr.astype(bool)
print(converted)


[False  True  True False  True]
[ True  True  True  True  True]


In [21]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [28]:
arr=np.linspace(0,1,100)
print(arr)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [20]:
arr=np.full((2,4),9)
print(arr)

[[9 9 9 9]
 [9 9 9 9]]


In [22]:

arr=np.array([[1,2,3],[4,5,6]])

print(np.ones_like(arr))


[[1 1 1]
 [1 1 1]]


In [41]:

arr2d=np.array([[10,20,30],
                [40,50,60]])


print(arr2d[1,2])

60


In [42]:
import numpy as np

arr=np.array([10,20,30,40,50])

print(arr[3])


# 2d


arr2d=np.array([[10,20,30],
                [40,50,60]])


print(arr2d[1,2])


arr3d=np.array([
    [[10,20],
    [30,45]],

[[46,70],
 [87,32]]])


# print(arr3d[0,1,1])
print(arr3d[1,1,0])

40
60
87


In [51]:

arr3d=np.array([
    [[10,20],
    [30,45]],

[[46,70],
 [87,32]]])


# print(arr3d[0,1,1])
print(arr3d[1,0,0])

46


Creating Arrays In Numpy


NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(type(arr))



# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

arrt=np.array((1,2,3,4,5))
print(type(arrt))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [1]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array((1,2,3))
print(type(arr1))
print(type(arr2))
print(arr1.ndim)
print(arr1.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
(3,)


In [27]:
# arr0d=np.array(12)
# print(arr0d)
# print(type(arr0d))
# print(arr0d.ndim)
# print(arr0d.shape)


# arr1d=np.array([1,2,3,4])
# print(arr1d.shape)
# print(arr1d.ndim)


# arr2d=np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4]])
# print(arr2d)
# print(arr2d.shape)

arr3d=np.array([[[1,2,3],[4,5,6]]])
print(arr3d.shape)
print(arr3d.ndim)

arr4d=np.array([1,2,3,4],ndmin=4)
print(arr4d.shape)

(1, 2, 3)
3
(1, 1, 1, 4)


Dimensions in Arrays


A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

In [35]:
arr0d = np.array([[[12,9723,32],[4,34,43]]],ndmin=5)

print(arr0d.ndim)
print(arr0d)
print()
print()

5
[[[[[  12 9723   32]
    [   4   34   43]]]]]




In [ ]:

# 0-D Arrays:

# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

import numpy as np

arr0d=np.array(42)

print(arr0d)
print(arr0d.shape)
print(arr0d.ndim)

<class 'numpy.ndarray'>
()
0
42
()
0


In [9]:
# 1-D Arrays:

# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

arr1d=np.array([1,2,3])
print(arr1d)
print(arr1d.shape)
print(arr1d.ndim)

[1 2 3]
(3,)
1


In [ ]:
# 2-D Arrays:

# An array that has 1-D arrays as its elements is called a 2-D array.

# These are often used to represent matrix or 2nd order tensors.

arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)



[[1 2 3]
 [4 5 6]]
(2, 3)
2
[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:

# 3-D arrays:

# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

# These are often used to represent a 3rd order tensor.


arr3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)



building=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(building)

int64
(2, 2, 2)
3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [29]:
building=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(building.shape)

(3, 3, 2)


In [1]:
# Check Number of Dimensions?

# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

import numpy as np

arr0d=np.array(43)
arr1d=np.array([1,2,3])
arr2d=np.array([[1,2,3],[4,5,6]])
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr0d.ndim)
print(arr1d.ndim)
print(arr2d.ndim)
print(arr3d.ndim)
print(arr2d.shape)
print(arr2d)


0
1
2
3
(2, 3)
[[1 2 3]
 [4 5 6]]


In [30]:


# Higher Dimensional Arrays:

# An array can have any number of dimensions.

# When the array is created, you can define the number of dimensions by using the ndmin argument.


arr=np.array([1,2,3,4],ndmin=5)
print(arr.ndim)
print(arr.shape)
print(arr)

arr2=np.array([1,2,3,4,5],ndmin=2)
print(arr2.ndim)

5
(1, 1, 1, 1, 4)
[[[[[1 2 3 4]]]]]
2





Practice Questions:-


Q-1: Create a 1D array with values [5,10,15,20,25].

->Print the array.

->Print its dimension and shape.


Q-2: Create a 1D array of numbers from 0 to 9.

->Verify that its 1D.

->Print its shape.


Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.

->Print the array.

->Print its ndim and shape.


Q-4: Create a 2D array (3*3) filled with numbers 1 to 9.

->Print the array.

->Verify its Dimension and Shape.


Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.

->Print the array.

->Print its shape and dimensions.

Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).

->Print the array.

->Print its dimension and shape.

Q-7 Create 4D array with shape(1,2,2,3).

->Print the array.

->Print its shape and dimensions.



In [17]:
# Q-1: Create a 1D array with values [5,10,15,20,25].
# ->Print the array.
# ->Print its dimension and shape.

import numpy as np
arr = np.array([5,10,15,20,25])
print(arr)
print(arr.ndim)
print(arr.shape)

[ 5 10 15 20 25]
1
(5,)


In [18]:
# Q-2: Create a 1D array of numbers from 0 to 9.
# ->Verify that its 1D.
# ->Print its shape.

arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr.ndim)
print(arr.shape)

1
(10,)


In [19]:
# Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.
# ->Print the array.
# ->Print its ndim and shape.

arr2D = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2D)
print(arr2D.ndim)
print(arr2D.shape)

[[1 2 3 4]
 [4 5 6 7]]
2
(2, 4)


In [20]:
# Q-4: Create a 2D array (3*3) filled with numbers 1 to 9.
# ->Print the array.
# ->Verify its Dimension and Shape.

arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2D)
print(arr2D.ndim)
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [21]:
# Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.
# ->Print the array.
# ->Print its shape and dimensions.

arr3D = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
(2, 3, 2)
3


In [22]:
# Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).
# ->Print the array.
# ->Print its dimension and shape.

arr3D = np.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
(2, 2, 3)
3


In [23]:
# Q-7 Create 4D array with shape(1,2,2,3).
# ->Print the array.
# ->Print its shape and dimensions.

arr4D = np.array([[
    [[1,2,3],[4,5,6]],
    [[7,8,9],[9,10,11]]
]])
print(arr4D)
print(arr4D.shape)
print(arr4D.ndim)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [ 9 10 11]]]]
(1, 2, 2, 3)
4


In [24]:
ar = np.array([[[[123,456,456]]]])
print(ar.ndim)
print(ar.shape)

4
(1, 1, 1, 3)


# Numpy Array Creation Functions:-

1.np.zeros(shape,dtype=float)

->Creates an array filled with zeros.

->shape->number of rows and columns(tuple).

->dtype-data type(default float)

In [25]:
import numpy as np

arr=np.zeros((2,3))
print("Array of zeros:\n",arr)
print("Shape:",arr.shape,"Dimension:",arr.ndim)
print(arr.dtype)

# Note:Default dtype is float64

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Shape: (2, 3) Dimension: 2
float64


In [27]:
import numpy as np

arr=np.ones((2,3,6))
print(arr)


arr=np.full((2,3,5),8)
print(arr)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]]


2. np.ones(shape,dtype=float)

Creates an array filled with ones.

In [2]:
arr=np.ones((3,2),dtype=int)
print("Array of ones:\n",arr)

Array of ones:
 [[1 1]
 [1 1]
 [1 1]]


3. np.full(shape,fill_value,dtype=None)

->Creates an array filled with any number we want(fill_value).

In [3]:
arr=np.full((2,2),7)
print("Full array:\n",arr)

Full array:
 [[7 7]
 [7 7]]


4. np.empty(shape,dtype=float)

->Creates an array without initializing values.

->Values are random(memory garbage)

In [6]:
arr=np.empty((2,3))
print("Empty array:\n",arr)

Empty array:
 [[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [31]:
arr=np.arange(1,11,2)
print(arr)


arr=np.linspace(0,1,10) # print value in between 0 to 1
print(arr)

[1 3 5 7 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


5. np.arange(start, stop, step)

->Creates a 1D array with numbers in range[start,stop]

->Step=diffrence between consecutive numbers.

In [32]:
arr=np.arange(0,10,2)
print(arr) 

[0 2 4 6 8]


6. np.linespace(start, stop, num)

->Creates evenly spaced numbers between start and stop.

->num=number of points.

In [33]:
arr=np.linspace(0,1,5)
print(arr)

# diffrence:arange->step size fix,linespace->number of points fix.

[0.   0.25 0.5  0.75 1.  ]


7. np.eye(N)/np.identity(N)

->Create an identity matrix (1 on diagonal,0 elsewhere)

In [34]:
arr=np.eye(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


8.Arrays with same shape as another(zeros_like,ones_like)

Useful when u want new array with same shape as exiting array.

In [35]:
a=np.array([[1,2,3],[4,5,6]])
print("Zeros like a:\n",np.zeros_like(a))

print("Ones like a:\n",np.ones_like(a))

Zeros like a:
 [[0 0 0]
 [0 0 0]]
Ones like a:
 [[1 1 1]
 [1 1 1]]


In [ ]:
# # arr1d=np.array([10,20,30,40,50])

# # print(arr1d[1])


# arr2d=np.array([[12,23], 
#                 [40,67]]) 

# # print(arr2d[0,1])

# # print(arr2d[0:2,1:2])


# arr3d=np.array([[[1,2],
#                  [4,5]],
                
#                 [[6,7],
#                  [8,9]]])

# # print(arr3d[1,0,1])
# # print(arr3d[0,1,1])

# print(arr3d[0:2,0:2,0:1])




# arr=np.array([10,20,30,40,50])

# print(arr[arr>30])



# arr=np.array([10,20,30,40,50])
# print(arr[0:3])


arr2d=np.array([[10,20,23],
                [43,45,67]])
# print(arr2d[1,1])
# print(arr2d[0,2])

print(arr2d[0:2,2:3])


# arr3d=np.array([[[87,90],
#                  [45,67]],

#                 [[12,34],
#                  [45,76]]])


# print(arr3d[0,1,1])
# print(arr3d[1,0,0])


# boolean indexing


# arr=np.array([10,20,30,40,50,60])
# print(arr[arr>30])


# fancy indexing


# arr=np.array([10,20,30,40,50])

# print(arr[[0,2,4]])

arr2d=np.array([[10,20,23],
                [43,45,67]])

print(arr2d[0:2,0:1])
print(arr2d[0:1,1:3])

[[23]
 [67]]
[[10]
 [43]]


----------------------------------------------------------------------------------------------------------

Practice Questions:


Q-1: Create a 2*3 array of zeros.Print dimension and shape.

Q-2: Create a 3*4 array of ones(int type).

Q-3: Create a 2*2 array filled with 9.

Q-4: Create an empty 2*3 array and print it.

Q-5: Create a 1D array of numbers from 10 to 50 with step=5 using arange.

Q-6: Create 5 evenly spaced numbers between 0 and 2 using linespace.

Q-7: Create a 4*4 identity matrix.

Q-8: Given array b=[[1,2,3],[4,5,6]],create zeros_like(b) and ones_like(b). 


----------------------------------------------------------------------------------------------------------

In [38]:
# Q-1: Create a 2*3 array of zeros.Print dimension and shape.

arr = np.zeros((2,3))
print(arr)
print(arr.shape)
print(arr.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
2


In [42]:
# Q-2: Create a 3*4 array of ones(int type).


# arr = np.ones((3,4))
# print(arr)

arr = np.ones((3,4),'int')
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [47]:
# Q-3: Create a 2*2 array filled with 9.

arr = np.full((2,2),9)
print(arr)

[[9 9]
 [9 9]]


In [48]:
# Q-4: Create an empty 2*3 array and print it.

arr = np.empty((2,3))
print(arr)

[[2.12199579e-314 2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314 2.12199579e-314]]


In [50]:
# Q-5: Create a 1D array of numbers from 10 to 50 with step=5 using arange.

arr = np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


In [53]:
# Q-6: Create 5 evenly spaced numbers between 0 and 2 using linspace.

arr = np.linspace(0,2,5)
print(arr)

[0.  0.5 1.  1.5 2. ]


In [54]:
# Q-7: Create a 4*4 identity matrix.

arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
# Q-8: Given array b=[[1,2,3],[4,5,6]],create zeros_like(b) and ones_like(b).

b = np.array([[1,2,3],[4,5,6]])
print("Zero like b:\n",np.zeros_like(b))
print("Ones like b:\n",np.ones_like(b))

Zero like b:
 [[0 0 0]
 [0 0 0]]
Ones like b:
 [[1 1 1]
 [1 1 1]]


In [63]:
import numpy as np

# arr=np.array(12)
# print(arr)
# print(type(arr))
# print(arr.shape)
# print(arr.ndim)

# arr1d=np.array([1,2,3,4])
# print(arr1d.ndim)
# print(arr1d)
# print(type(arr1d))
# print(arr1d.shape)

# arr2d=np.array([[1,2,3,4],[5,6,7,8]])

# print(arr2d)
# print(arr2d.shape)
# print(arr2d.ndim)


# arr3d=np.array([[[1,2,3,4]]])
# print(arr3d)
# print(arr3d.shape)
# print(arr3d.ndim)


arr3d=np.array([[[1,2],
                 [3,4]],

                [[5,6],
                 [7,8]]])


print(arr3d)
print(arr3d.shape)

(1,4,2)

12
<class 'numpy.ndarray'>
()
0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


(1, 4, 2)

In [66]:
import numpy as np

# arr0d=np.array(12)
# print(arr0d.ndim)
# print(type(arr0d))
# print(arr0d.shape)


# arr1d=np.array([1,2,3,4,5])
# print(arr1d)
# print(arr1d.ndim)
# print(arr1d.shape)


arr2d=np.array([[1,2,3,4],[10,20,30,40]])
# print(arr2d)
# print(arr2d.ndim)
# print(arr2d.shape)


# (3,4)

# arr2d=np.array([[1,2,3,4],[5,6,7,8],[10,23,24,25]])
# print(arr2d)


# arr3d=np.array([[[1,2,3,4]]])
# print(arr3d)
# print(arr3d.shape)
# print(arr3d.ndim)



# arr3d=np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
# print(arr3d)
# print(arr3d.shape)


# (1,5,2)


# arr3d=np.array([[[1,2],[4,5],[6,7],[8,0],[10,11]]])

# print(arr3d)

# zeros

# arr=np.zeros((2,3,8))
# print(arr)


# arr1=np.ones((3,4))
# print(arr1)

# arr=np.full((3,5,7),9)
# print(arr)


# arr=np.arange(1,11,2)
# print(arr)

# arr=np.linspace(0,1,10)
# print(arr)


# arr=np.array([1,2,3,4,5],ndmin=64)
# print(arr.shape)
# print(arr.ndim)



# arr3d=np.array([[[23,45],
#                  [67,89],
#                  [90,65]],

#                 [[12,34],
#                  [56,78],
#                  [37,98]]])

# print(arr3d[1:2,2:3,0:2])
# print(arr3d[1:2,0:3,1:2])

In [67]:
import numpy as np


# arr0d=np.array(12)
# print(arr0d)
# print(arr0d.ndim)
# print(arr0d.shape)


# arr1d=np.array([1,2,3,5,6])
# # print(type(arr1d))
# print(arr1d.ndim)
# print(arr1d.shape)


# arr2d=np.array([[1,2,3,4,5],[10,20,30,40,50]])
# print(arr2d)
# print(arr2d.shape)


# arr3d=np.array([[[1,2,3,4]]])
# print(arr3d.ndim)
# print(arr3d.shape)

# arr3d=np.array([[[12,34],
#                  [56,78]],
                
#                 [[100,120],
#                  [36,78]]])

# (2,2,2)

# (2,3,4)
# print(arr3d.shape)

# arr3d=np.array([[[1,2,3,4],
#                  [5,6,7,8],
#                  [9,10,11,12]],
                
#                 [[13,14,15,16],
#                  [17,18,19,20],
#                  [21,23,24,25]]])


# print(arr3d)

# arr10d=np.array([1,2,3,4,5],ndmin=64)
# print(arr10d)


# arr0s=np.zeros((2,3,3))
# print(arr0s)

# arr1s=np.ones((2,3,4))
# print(arr1s)


# arrfs=np.full((2,3,3),4)
# print(arrfs)



# arr=np.arange(1,11,2)
# print(arr)

ar=np.linspace(0,1,10)
print(ar)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [69]:
import numpy as np


# arr0d=np.array(12)
# print(arr0d)
# print(arr0d.ndim)
# print(arr0d.shape)


# arr1d=np.array([1,2,3,4,5])

# print(arr1d.ndim)
# print(arr1d.shape)
# print(type(arr1d))


# arr2d=np.array([[10,20,30],[40,50,60]])

# print(arr2d.ndim)
# print(arr2d.shape)


# (3,3)

# arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(arr.shape)

# (2,6)

# arr2d=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

# print(arr2d.shape)

# (3,2)


# arr=np.array([[1,2],[3,4],[5,6]])
# print(arr.shape)


# arr3d=np.array([[[1,2,3]]])

# print(arr3d.shape)


# print(arr3d.ndim)



# arr3d=np.array([[[1,2],
#                  [3,4]],
                
#                 [[5,6],
#                  [7,8]]])

# print(arr3d.shape)
# print(arr3d)


# (2,3,2)


# arr3d=np.array([[[1,2],
#                  [3,4],
#                  [5,6]],
                
#                 [[7,8],
#                  [9,10],
#                  [11,12]]])
# print(arr3d.shape)


# (1,2,3)


# arr=np.array([[[1,2,3],[4,5,6]]])



arr=np.array([1,2,3,4,5],ndmin=10)
print(arr.ndim)

10


In [70]:
import numpy as np

# arr=np.ones((3,4))
# print(arr)

# arr=np.full((2,3,8),12)
# print(arr)


# arr=np.arange(1,11)
# print(arr)


# arr=np.arange(1,100,2)
# print(arr)


# arr=np.linspace(0,1,10)
# print(arr)

# arr=np.linspace(1,10,5)
# print(arr)

# arr=np.array([[1,2,3],[5,6,7]])
# print(arr)

# print("zeros like",np.zeros_like(arr))
# print("ones like:\n",np.ones_like(arr))




In [71]:
import numpy as np


arr=np.array([10,20,30,40,50])

# print(arr[1])


# arr2d=np.array([[10,12,34],
#                 [45,67,89]])


# print(arr2d[1,1])
# print(arr2d[1,2])


# arr3d=np.array([[[13,45,76],
#                  [89,90,92]],

#                 [[56,76,34],
#                  [89,23,43]]])


# print(arr3d[1,0,2])

# print(arr3d[0,1,1])

# print(arr3d[1,0,0])


arr=np.array([10,20,30,40,50])

# boolean indexing

# print(arr[arr>20])

# fancy indexing

print(arr[[0,2,4]])


[10 30 50]


In [ ]:
import numpy as np


# arr=np.zeros((2,3,4))
# print(arr)


# arr=np.ones((2,3))
# print(arr)

# arr=np.full((2,3),2)
# print(arr)


# arr=np.arange(10)
# print(arr)

# arr=np.empty((2,3))
# print(arr)


# arr=np.linspace(0,10,10)
# print(arr)


# arr=np.eye(10)
# print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
