In [10]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr[1:3])
# print(arr[2:3]) #1D


[20 30]


In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

arr[2:-3]

array([3, 4, 5])

In [12]:
arr=np.array([[10,20,30],
              [40,50,60]])
# print(arr)

print(arr[1,2]) 

60


In [13]:
#2D

In [14]:
arr=np.array([[[10,20,30],
               [40,50,60]],
               
               [[70,80,90],
                [100,110,120]]])

# print(arr)
print(arr[1,1,1])
print(arr[0,1,2])
# print(arr[1,0,2])
# print(arr[1,0,0])

110
60


In [15]:
import numpy as np

arr=np.array([10,20,30,40,50,60,70])

print(arr[0:3])
print(arr[5:7])
print(arr[5:-1])

[10 20 30]
[60 70]
[60]


In [16]:
arr=np.array([[1,2,3],
              [4,5,6]])

print(arr[0:2,0:2])

# print(arr[0:1,0:2]) #2d

[[1 2]
 [4 5]]


In [17]:
arr=np.array([[[10,20,30],
               [40,50,60]],
               
               [[70,80,90],
                [100,110,120]]])

In [18]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[arr>4]
# print()

array([5, 6, 7, 8])

In [19]:

# print(arr[0:2,1:2,0:2])

# boolean slicing




# fancy indexing

arr=np.array([10,23,30,40,50,60,70])
print(arr[arr%2==0])
print(arr[[0,3,5]])

[10 30 40 50 60 70]
[10 40 60]


# Array Indexing:-


Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [20]:
import numpy as np 

arr=np.array([10,20,30,40,50])
print(arr[1])

print(arr[1]+arr[2])

20
50


In [21]:
import numpy as np

arr1d=np.array([10,20,30,40,50])


arr2d=np.array([[10,20,30],
                [40,50,60]])

print(arr2d[-1,-1])


arr3d=np.array([[[10,20,30],
                 [40,50,60]]

                ,[[70,80,90],
                  [100,110,120]]])
print(arr3d[0,1,2])

60
60


# Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

syntax=[row*col]

rows and columns both start at 0.

In [22]:
arr2d=np.array([[10,20,30],
                [40,50,60]])
print(arr2d)
print(arr2d[1,2])
print(arr2d[1,1])
print(arr2d[0,:])

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(arr[0,0]) #first row, first col
print(arr[1,2]) #second row, third col
print(arr[-1,-1]) #last row last col



[[10 20 30]
 [40 50 60]]
60
50
[10 20 30]
1
6
9


# Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [23]:
arr3d=np.array([
                [[10,20,30],
                 [40,50,60]],

                [[70,80,90],
                 [100,200,300]],

                [[1,2,3],
                 [1,999,3]]
                 ]
                 )
# print(arr3d)
# print(arr3d[1,1,1])
print(arr3d[1,1,2])
# print(arr3d[2,1,1])
# print(arr3d[1,1,-1])
# print(arr3d[1,1])

300


In [24]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d[1,-1])
print(arr2d[0,-2])

[[1 2 3]
 [4 5 6]]
6
2


In [25]:
# Boolean Indexing(conditions)

# Select elements that satisfy condition

arr=np.array([10,20,30,40,50])
print(arr[arr>25]) #elements>25
print(arr[arr%20==0]) #divisible by 20


arr=np.array([10,20,30,40,50,60])
print(arr[arr>30])


[30 40 50]
[20 40]
[40 50 60]


In [36]:
# Fancy indexing(specific positions)

# use a list/array of indices

arr=np.array([10,20,30,40,50])
print(arr[[0,2,4]]) #pick 1st,3rd,5th elemtns

arr2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr2d[[0,2],[1,2]])

[10 30 50]
[2 9]


In [31]:
# Modifying Using indexing

arr=np.array([1,2,3,4,5])
arr[2]=99
print(arr)

# slicing 
arr[1:4]=0
print(arr)

[ 1  2 99  4  5]
[1 0 0 0 5]


# NumPy Array Slicing


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1


syntax=[start:end:step]


In [39]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr[::-1])
print(arr[4:])

arr=np.array([10,20,30,40,50,60])
print(arr[1:4]) #from index 1 to 3
print(arr[:3]) #first 3 elements
print(arr[::2]) #every second element
print(arr[::-1]) #reverse array


[6 5 4 3 2 1]
[5 6]
[20 30 40]
[10 20 30]
[10 30 50]
[60 50 40 30 20 10]


In [41]:

# Slicing 2-D Arrays

import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# print(arr[:,1:3])#rows 0-1, cols 1-2
# print(arr[:,1]) #all rows, col index 1
# print(arr[1,:]) #row index 1, all columns

# arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# print(arr1)
# print(arr1[1, 1:5])


# arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# print(arr2[0:2, 3])


# arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# print(arr2[0:2, 1:4])



arr3d=np.array([
    [[10,20],
    [30,40]]

,  [[50,60],
   [70,80]],

[[90,100],
[110,120]]
])


print(arr3d[0:1,1,0])

[30]


----------------------------------------------------------------------------------------------------------


Practice Questions:-


<!-- Basic Indexing 1D-->

Q-1: Create an array [10,20,30,40,50,60,70,80,90].

->Get the first element.

->Get the last element.

->Get the 4th element.

->Get elements at positions [0,3,5].


Q-2: Reverse the above array.

Q-3: Replace the 2nd and 3rd elements with [999,888].



<!-- Basic Indexing 2D -->

arr=[[11,12,13],
      [21,22,23],
      [31,32,33],
      [41,42,43]]


Q-4:Get element in 2nd row, 3rd column.

Q-5:Get element in last row, last column.

Q-6:Get the first column only.

Q-7:Get the last row only.

Q-8:Replace the value at position (1,1) with 999.




<!-- Slicing 1D -->


Q-9:From [5,10,15,20,25,30,35,40]:

->Extract [10,15,20].

->Extract [5,15,25,35].

->Extract every second element.

->Extract elements from index 2 till end.



<!-- Slicing 2D -->

arr=[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]


Q-10:Extract first 2 rows and first 2 columns.

Q-11:Extract last 2 rows and last 2 columns.

Q-12:Extract the middle 2*2 submatrix (,7,10,11).

Q-13:Extract all rows but only the 3rd column.

Q-14:Extract all columns but only the 2nd row.

Q-15:Reverse the order of rows.

Q-16:Reverse the order of columns.




<!-- Boolean Indexing -->

Q-17:From [10,15,20,25,30,35,40]:

->Extract all values greater than 20.

->Extract even numbers.

->Extract numbers divisible by 5 but less than 30.


Q-18:Replace all odd numbers with -1 in [1,2,3,4,5,6,7,8,9].

Q-19:From a 2D array,extract all values greater than 10.




<!-- Fancy Indexing -->

Q-20:Given [100,200,300,400,500,600], pick elements at position [0,2,4].

Q-21:From the 2D array:

[[1,2,3],
[4,5,6],
[7,8,9]]

->Extract (0,1) and (2,2).

->Extract elements at row indices [0,2] and col indices [0,1].


Q-22:Shuflle the rows of the above 2D array using fancy indexing.




<!-- Real Dataset Style Questions -->


Q-23:You have student scores array:

scores=np.array([56,72,89,45,68,91,77])

->Extract students who scored more than 70.

->Extract students who failed(<50).

->Replace all scores below 50 with 0.


Q-24:You have temperature data(celecius) for a week:

temps=np.array([32,35,30,29,40,38,31])

->Get temperatures of weekdays only(first 5).

->Get weekend temps(last 2).

->Get days where temp>35.


Q-25:You have sales data of 4 products across 5 days:

sales=np.array([
    [12,15,20,22,18],
    [14,18,24,20,25],
    [10,12,15,18,22],
    [20,22,19,24,30]
])

->Extract sales of product 1 for all days.

->Extract sales of day 3 for all products.

->Extract sales of first 2 products for first 3 days.

->Find all sales<20.

->Replace all sales<15 with 0.


Q-26:You have dataset of customers ages:

ages=np.array([15,22,35,42,60,18,25,55])

->Extract all customers older than 30.

->Extract customers between 18 and 25.

->Replace all ages above 50 with 50.


Q-27:You have marks of students in 3 subjects:


marks=np.array([
    [80,70,90],
    [60,75,85],
    [95,88,92],
    [40,65,70]
])

->Extract marks of subject 2 for all students.

->Extract marks of student 3 across all subjects.

->Extract students who scored > 80 in subject 1.

->Extract students whose average marks>75.






<!-- Where this is used in real data -->

1.Feature selection->choosing specific columns from dataset(arr[:,[1,3]]).

2.Filtering rows->selecting only rows with certain conditipon(arr[arr[:,2]>50]).

3.Capping values->Replacing outliers with thresold(arr[arr<100]=100).

4.Splitting train/test data->indexing with slicing (arr[:80] for train, arr[80:] for test).

5.Reversing sequences->time-series reversal(arr[::-1]).

6.Picking specific samples->fancy indexing with random slices (arr[[2,5,7]])


----------------------------------------------------------------------------------------------------------

In [48]:
# Q-1: Create an array [10,20,30,40,50,60,70,80,90].
# ->Get the first element.
# ->Get the last element.
# ->Get the 4th element.
# ->Get elements at positions [0,3,5].

arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[0])
print(arr[8])
print(arr[3])
print(arr[[0,3,5]])

10
90
40
[10 40 60]


In [50]:
# Q-2: Reverse the above array.

arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[::-1])

[90 80 70 60 50 40 30 20 10]


In [56]:
# Q-3: Replace the 2nd and 3rd elements with [999,888].
# arr=[[11,12,13], [21,22,23], [31,32,33], [41,42,43]]

arr=[[11,12,13], [21,22,23], [31,32,33], [41,42,43]]

arr[1] = 999
arr[2] = 888
print(arr)

[[11, 12, 13], 999, 888, [41, 42, 43]]


In [59]:
# Q-4:Get element in 2nd row, 3rd column.

arr=np.array([[11,12,13], 
     [21,22,23], 
     [31,32,33], 
     [41,42,43]])

print(arr[1,2])

23


In [60]:
# Q-5:Get element in last row, last column.

arr=np.array([[11,12,13], 
     [21,22,23], 
     [31,32,33], 
     [41,42,43]])

print(arr[3,2])

43


In [61]:
# Q-6:Get the first column only.

arr=np.array([[11,12,13], 
     [21,22,23], 
     [31,32,33], 
     [41,42,43]])

print(arr[:,0])

[11 21 31 41]


In [62]:
# Q-7:Get the last row only.

arr=np.array([[11,12,13], 
     [21,22,23], 
     [31,32,33], 
     [41,42,43]])

print(arr[-1])

[41 42 43]


In [66]:
# Q-8:Replace the value at position (1,1) with 999.

arr=np.array([[11,12,13], 
     [21,22,23], 
     [31,32,33], 
     [41,42,43]])

arr[1,1] = 999

print(arr)

[[ 11  12  13]
 [ 21 999  23]
 [ 31  32  33]
 [ 41  42  43]]


In [71]:
# Q-9:From [5,10,15,20,25,30,35,40]:
# ->Extract [10,15,20].
# ->Extract [5,15,25,35].
# ->Extract every second element.
# ->Extract elements from index 2 till end.

arr = np.array([5,10,15,20,25,30,35,40])

print(arr[1:4])
print(arr[0:7:2])
print(arr[::2])
print(arr[2:])

[10 15 20]
[ 5 15 25 35]
[ 5 15 25 35]
[15 20 25 30 35 40]


In [73]:
# Q-10:Extract first 2 rows and first 2 columns.

arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])

print(arr[1,1])

6


In [74]:
# Q-11:Extract last 2 rows and last 2 columns.

arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])
print(arr[2,2])

11


In [81]:
# Q-12:Extract the middle 2*2 submatrix (6,7,10,11). 



arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])

print(arr[1:3,1:3])

# 1:3 (rows) → 2nd aur 3rd row
# 1:3 (columns) → 2nd aur 3rd column

[[ 6  7]
 [10 11]]


In [82]:
# Q-13:Extract all rows but only the 3rd column.

arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])

print(arr[:,2])

[ 3  7 11 15]


In [83]:
# Q-14:Extract all columns but only the 2nd row.

arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])

print(arr[1,:])

[5 6 7 8]


In [85]:
# Q-15:Reverse the order of rows.

arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])

print(arr[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [86]:
# Q-16:Reverse the order of columns.

arr=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])

print(arr[:,::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [95]:
# Q-17:From [10,15,20,25,30,35,40]:
# ->Extract all values greater than 20.
# ->Extract even numbers.
# ->Extract numbers divisible by 5 but less than 30.

arr = np.array([10,15,20,25,30,35,40])
print(arr[arr>20]) #elements>20
print(arr[arr%2==0])
print(arr[(arr%5==0) & (arr<30)])

[25 30 35 40]
[10 20 30 40]
[10 15 20 25]


In [96]:
# Q-18:Replace all odd numbers with -1 in [1,2,3,4,5,6,7,8,9].

arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr%2!=0] = [-1]
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [99]:
# Q-19:From a 2D array,extract all values greater than 10.

arr = np.array([[1,2,30,5],[11,7,60,85]])
result_arr = arr[arr>10]
print(result_arr)

[30 11 60 85]


In [101]:
# Q-20:Given [100,200,300,400,500,600], pick elements at position [0,2,4].

arr = np.array([100,200,300,400,500,600])
print(arr[[0,2,4]])

[100 300 500]


In [120]:
# Q-21:From the 2D array:
# [[1,2,3], [4,5,6], [7,8,9]]
# ->Extract (0,1) and (2,2).
# ->Extract elements at row indices [0,2] and col indices [0,1].

arr = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

print(arr[0:2,2:3])

print(arr[0:3,0:2])

[[3]
 [6]]
[[1 2]
 [4 5]
 [7 8]]


In [121]:
# Q-22:Shuflle the rows of the above 2D array using fancy indexing.
arr = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])
shuffled = arr[[2,0,1]]
print(shuffled)

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [124]:
# Q-23:You have student scores array:
# scores=np.array([56,72,89,45,68,91,77])
# ->Extract students who scored more than 70.
# ->Extract students who failed(<50).
# ->Replace all scores below 50 with 0.

scores=np.array([56,72,89,45,68,91,77])

scored = scores[scores >70]
print(scored)

failed = scores[scores<50]
print(failed)

scores[scores<50] = 0
print(scores)

[72 89 91 77]
[45]
[56 72 89  0 68 91 77]


In [136]:
# Q-24:You have temperature data(celecius) for a week:
# temps=np.array([32,35,30,29,40,38,31])
# ->Get temperatures of weekdays only(first 5).
# ->Get weekend temps(last 2).
# ->Get days where temp>35.

temps=np.array([32,35,30,29,40,38,31])


weekdays = temps[:5]
print(weekdays)


# weekend = temps[5:7] # or 
weekend = temps[-2:]
print(weekend)


days = temps[temps>35]
print(days)

[32 35 30 29 40]
[38 31]
[40 38]


In [5]:
# Q-25:You have sales data of 4 products across 5 days:
# sales=np.array([ [12,15,20,22,18], [14,18,24,20,25], [10,12,15,18,22], [20,22,19,24,30] ])

# ->Extract sales of product 1 for all days.

# ->Extract sales of day 3 for all products.
# ->Extract sales of first 2 products for first 3 days.
# ->Find all sales<20.
# ->Replace all sales<15 with 0.

import numpy as np

sales=np.array([ [12,15,20,22,18], 
                 [14,18,24,20,25], 
                 [10,12,15,18,22], 
                 [20,22,19,24,30] ])

product1 = sales[0,:]
print(product1)

day3 = sales[:,2]
print(day3)

subset = sales[:2,:3]
print(subset)

low_sales = sales[sales<20]
print(low_sales)

sales[sales<15] = 0

print(sales)

[12 15 20 22 18]
[20 24 15 19]
[[12 15 20]
 [14 18 24]]
[12 15 18 14 18 10 12 15 18 19]
[[ 0 15 20 22 18]
 [ 0 18 24 20 25]
 [ 0  0 15 18 22]
 [20 22 19 24 30]]


In [9]:
# Q-26:You have dataset of customers ages:
# ages=np.array([15,22,35,42,60,18,25,55])
# ->Extract all customers older than 30.
# ->Extract customers between 18 and 25.
# ->Replace all ages above 50 with 50.

ages=np.array([15,22,35,42,60,18,25,55])

older_customers = ages[ages>30]
print(older_customers)

between_18_25 = ages[(ages>=18)&(ages<=25)]
print(between_18_25)

ages_modified = ages.copy()
ages_modified[ages>=50] = 50
print(ages)

[35 42 60 55]
[22 18 25]
[15 22 35 42 60 18 25 55]


In [15]:
# Q-27:You have marks of students in 3 subjects:

# marks=np.array([ [80,70,90], [60,75,85], [95,88,92], [40,65,70] ])
# ->Extract marks of subject 2 for all students.
# ->Extract marks of student 3 across all subjects
# ->Extract students who scored > 80 in subject 1.
# ->Extract students whose average marks>75.


marks=np.array([ [80,70,90], 
                 [60,75,85], 
                 [95,88,92], 
                 [40,65,70] ])

subject2 = marks[:,1]
print(subject2)

student3 = marks[2,:]
print(student3)

subject1_above_80 = marks[marks[:,0] > 80]
print(subject1_above_80)

avg_above_75 = marks[marks.mean(axis=1) > 75]
print(avg_above_75)

[70 75 88 65]
[95 88 92]
[[95 88 92]]
[[80 70 90]
 [95 88 92]]


In [16]:
# 1.Feature selection->choosing specific columns from dataset(arr[:,[1,3]]).

arr = np.array([
    [10, 20, 30, 40],
    [11, 21, 31, 41],
    [12, 22, 32, 42]
])

selected_features = arr[:, [1,3]]
print(selected_features)

[[20 40]
 [21 41]
 [22 42]]


In [17]:
# 2.Filtering rows->selecting only rows with certain conditipon(arr[arr[:,2]>50]).

arr = np.array([
    [10, 20, 60],
    [15, 25, 40],
    [30, 35, 80],
    [12, 18, 55]
])

filtered_rows = arr[arr[:, 2] > 50]
print(filtered_rows)

[[10 20 60]
 [30 35 80]
 [12 18 55]]


In [18]:
# 3.Capping values->Replacing outliers with thresold(arr[arr<100]=100).

arr = np.array([ [80,70,90], [60,75,85], [95,88,92], [40,65,70] ])

arr[arr<100]=100
print(arr)

[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]]


In [20]:
# 4.Splitting train/test data->indexing with slicing (arr[:80] for train, arr[80:] for test).

arr = np.array([ [80,70,90], [60,75,85], [95,88,92], [40,65,70] ])

print(arr[:80])
print(arr[80:])

[[80 70 90]
 [60 75 85]
 [95 88 92]
 [40 65 70]]
[]


In [21]:
# 5.Reversing sequences->time-series reversal(arr[::-1]).

arr = np.array([ [80,70,90], [60,75,85], [95,88,92], [40,65,70] ])

print(arr[::-1])

[[40 65 70]
 [95 88 92]
 [60 75 85]
 [80 70 90]]


In [23]:
# 6.Picking specific samples->fancy indexing with random slices (arr[[2,5,7]])

arr = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [95, 88, 92],
    [40, 65, 70],
    [55, 60, 75],
    [90, 85, 88],
    [72, 78, 80],
    [68, 70, 74]
])

print(arr[[2,5,7]])

[[95 88 92]
 [90 85 88]
 [68 70 74]]


In [7]:
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(x[:1])

# ->Extract (0,1) and (2,2).

# ->Extract elements at row indices [0,2] and col indices [0,1].

[[1 2 3]]


In [42]:
  # arr=[12,15,20,22,18],
  #   [14,18,24,20,25],
  #   [10,12,15,18,22],
  #   [20,22,19,24,30]

In [43]:
# arr[arr>75]


# arr[::-1]
# arr[:,:,::-1]

In [ ]:
import numpy as np


# arr=np.array([10,20,30,40,50])

arr2d=np.array([[10,20,30],
                [40,50,60]])

print(arr2d[0:1])


# print(arr3d[1,0,2])


# boolean indexing


# arr=np.array([1,2,3,4,5,6,7,8])

# print(arr[[2,5,3]])
# # print(arr[arr>2])



# arr=np.array([1,2,3,4,5])

# print(arr[0:2])



[[10 20 30]]


In [40]:
# arr3d=np.array([[[10,20,30],
#                  [40,50,60]],

#                 [[45,67,89],
#                  [34,56,78]]])


# print(arr3d[0:2,0:1,0:1])


# arr=np.array([1,2,3,4,5,0],dtype='bool')
# print(arr)


# arr=np.array([1.2,3.4,5.6,7.8])
# converted=arr.astype('int')
# print(converted.dtype)


arr=np.array([[[1,2,3],[10,20,30]],
              [[12,34,56],[78,90,89]]])


# for row in arr:
#     for col in row:
#      print(col)



# for block in arr:
#     for row in block:
#         for col in row:
#             print(col)


# for i in np.nditer(arr):
#     print(i)


# enumerate


for index,i in np.ndenumerate(arr):
    print(index,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 10
(0, 1, 1) 20
(0, 1, 2) 30
(1, 0, 0) 12
(1, 0, 1) 34
(1, 0, 2) 56
(1, 1, 0) 78
(1, 1, 1) 90
(1, 1, 2) 89
