# NumPy Array Iterating

Iteration in numpy arrays ke elements ko loop karne ka tarika hai,or ye python loops se thora diffrent or optimized hota hai.


so today we started learning nlp now the topic is pipeline what do u mean by pipe line its like squence of something or something fited one behind another like so that way when e want to gave a data to machine we have to provide good data efficient data so machine predict or work on that data efficintly and gave better accuracy so in that sense when we talking about nlp we like we have data like my name is sumit jadav so if we direclt gave this data withoutpreprocessing cleaning and like that so machine acuray definatly gets affected right so we have to first make a perfect text and this thing is done by nlp thats what nlp do means natarual which we speak like common enlish lagauge will be processed under this concept so full name is natural lanugage processing

and when we talk about piepline its means the steps included in this natural lauge processing the way we cleaned is fited line by line in sequence so thats why we call it pipeline is that clear.

now we talk about nltk and spicy its a library of python which i work as base languge to perform all the opeartions of nlp task so basicaly we show eample of every step which we done to process text 


so today we and when we talk abot pieplin its means the steps included in this natural lagunge processing the way we cleaned is fited line by line in sequence so that why we call it piepline is that clear/
now ee tlk about nltk and spicy its a library of puython which i work as base lanuge to perfomr all the operations of nlp task so basiclly we show example of every stpe which we de to process tect


so today we and when we talk about piepline its means the steps included in this natural lanuge processsing the way we cleaned is fited lie by line in seuqnce in now see talk baout nltk and spicy its a library

In [17]:
import numpy as np

a = np.array([[[[[1,2,3,4],[5,6,7,8]]]]])

for i in a:
    for j in i:
        for k in j:

            print(k)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
import numpy as np
ar =  np.array([[1,2,3,4,5]])

for i in ar:
    for j in i:
        print(j)

1
2
3
4
5


In [19]:
# Iterating 1D array
import numpy as np


arr=np.array([[1,2,3,4,5]])

for a in arr:
    print(a)


[1 2 3 4 5]


In [14]:
# Iterating 2D array

arr2d=np.array([[[1,2,3]
                ,[4,5,6]]])

for row in arr2d:
    for j in row:
        print(j)


[1 2 3]
[4 5 6]


In [15]:
# Iterating n-D arrays(ndim>2)

arr3d=np.arange(12).reshape(2,2,3)

arr3d.reshape(-1)

# shape(2,2,3)->2 blocks,2 rows, 3columns

for block in arr3d:
    for row in block:
        for columns in row:
            print(columns)    


0
1
2
3
4
5
6
7
8
9
10
11


# Iterating Arrays Using nditer()

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [9]:
arr=np.array([[[1,2,3],[4,5,6]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [10]:
# 3.Iterating with broadcasting

a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

for x,y in np.nditer([a,b]):
    print(x,'+',y,'=',x+y)

1 + 10 = 11
2 + 10 = 12
3 + 10 = 13
1 + 20 = 21
2 + 20 = 22
3 + 20 = 23
1 + 30 = 31
2 + 30 = 32
3 + 30 = 33


Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [12]:
import numpy as np

arr=np.array([[1,2,3,4],[4,3,2,1]])

for index,i in np.ndenumerate(arr):
    print(index,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 4
(1, 1) 3
(1, 2) 2
(1, 3) 1


In [16]:
arr2d=np.array([[1,2,3],[4,5,6]])

for index,i in np.ndenumerate(arr2d):
    print(index,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


Adavance iteration techniques

In [12]:
# 1.Flatten array before iteration

arr=np.array([[1,2,3],[4,5,6]])

for x in arr.flatten():
    print(x)

1
2
3
4
5
6


In [10]:
# 2.Vectorized operations(preffered over iteration)

arr=np.array([1,2,3,4])
arr2=arr*2
print(arr2)

[2 4 6 8]


In [2]:
import numpy as np
arr=np.array([1,2,3,4])

arr= arr*arr
print(arr)

[ 1  4  9 16]


# Practical Questions

Q-1: Create a 1D NumPy array of numbers 0-9.

->Iterate using a normal for loop and print each element.

->Then multiply each element by 2 using a loop, not vectorized.


Q-2: Create a 2D array of shape(3,4) with values 0-11.

->Print each rows separately.

->Print all elements using nested loops.

->Flatten the array and iterate as a 1D array.


Q-3: Create a (2,3) array with values 10-15.

->Iterate over all elements using np.nditer.

->Modify the array in-place so that each element become its square.




Q-4: Given Two arrays:

a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

->Use np.nditer([a,b]) to print their sum element wise.

->Check how broadcasting works.


Q-5: Create a 2D array of shape(3,3) with values 1-9.

->Use np.ndenumerate to print index and value of each element.

->Replace all elements at even row indices with 0.


Q-6: Create a (2,2,3) array using np.arange(12).

->Iterate block by block(normal loops).

->Iterate element by element using np.nditer.

->Use np.ndenumerate to print(i,j,k) index with its value.



In [21]:
# Q-1: Create a 1D NumPy array of numbers 0-9.
# ->Iterate using a normal for loop and print each element.
# ->Then multiply each element by 2 using a loop, not vectorized.

arr = np.array([0,1,2,3,4,5,6,7,8,9])

for i in arr:
    print(i)
    
    
for i in range(len(arr)):
    arr[i] = arr[i] * 2

print(arr)

0
1
2
3
4
5
6
7
8
9
[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
# Q-2: Create a 2D array of shape(3,4) with values 0-11.
# ->Print each rows separately.
# ->Print all elements using nested loops.
# ->Flatten the array and iterate as a 1D array.

import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

for row in arr:
    print(row)
    
    
for i in arr:
    for j in i:
        print(j)
        
flat_arr = arr.flatten()
print(flat_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
# Q-3: Create a (2,3) array with values 10-15.
# ->Iterate over all elements using np.nditer.
# ->Modify the array in-place so that each element become its square.

arr = np.arange(10,16).reshape(2,3)
print(arr)

for x in np.nditer(arr):
    print(x)
    
for i in range(len(arr)):
    arr[i] = arr[i] * arr[i]
    
print(arr)

[[10 11 12]
 [13 14 15]]
10
11
12
13
14
15
[[100 121 144]
 [169 196 225]]


In [14]:
# Q-4: Given Two arrays:
# a=np.array([1,2,3]) b=np.array([[10],[20],[30]])
# ->Use np.nditer([a,b]) to print their sum element wise.
# ->Check how broadcasting works.

a=np.array([1,2,3]) 

b=np.array([[10],[20],[30]])

for x,y in np.nditer([a,b]):
    print(x,'+',y,'=',x+y)
    
    
# a → [[1 2 3]
#      [1 2 3]
#      [1 2 3]]

# b → [[10 10 10]
#      [20 20 20]
#      [30 30 30]]

# Output:
    
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]

1 + 10 = 11
2 + 10 = 12
3 + 10 = 13
1 + 20 = 21
2 + 20 = 22
3 + 20 = 23
1 + 30 = 31
2 + 30 = 32
3 + 30 = 33


In [19]:
# Q-5: Create a 2D array of shape(3,3) with values 1-9.
# ->Use np.ndenumerate to print index and value of each element.
# ->Replace all elements at even row indices with 0.

import numpy as np

arr = np.arange(1,10).reshape(3,3)

print(arr)

for index,i in np.ndenumerate(arr):
    print(index,i)
    
for (i,j),val in np.ndenumerate(arr):
    if i%2==0:
        arr[i,j] =0
print(arr)        


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
[[0 0 0]
 [4 5 6]
 [0 0 0]]


In [26]:
# Q-6: Create a (2,2,3) array using np.arange(12).
# ->Iterate block by block(normal loops).
# ->Iterate element by element using np.nditer.
# ->Use np.ndenumerate to print(i,j,k) index with its value.

arr = np.arange(12).reshape(2,2,3)
print(arr)

for i in arr:
    for j in i:
        print(j)
        
for x in np.nditer(arr):
    print(x)
    
for index,i in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {i}")

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11
Index: (0, 0, 0), Value: 0
Index: (0, 0, 1), Value: 1
Index: (0, 0, 2), Value: 2
Index: (0, 1, 0), Value: 3
Index: (0, 1, 1), Value: 4
Index: (0, 1, 2), Value: 5
Index: (1, 0, 0), Value: 6
Index: (1, 0, 1), Value: 7
Index: (1, 0, 2), Value: 8
Index: (1, 1, 0), Value: 9
Index: (1, 1, 1), Value: 10
Index: (1, 1, 2), Value: 11


In [ ]:
import numpy as np

arr=np.arange(12).reshape(2,2,3)
print(arr)


# for block in arr:
#     for row in block:
#         for col in row:
#             print(col)



for i in np.nditer(arr):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
import numpy as np


arr=np.array([[[1,2,3,4,5],[10,20,30,40,50]],[[1,2,3,4,5],[10,20,30,40,50]]])

# for block in arr:
#     for row in block:
#         for col in row:
#             print(col)
    
for i in np.nditer(arr):
    print(i)



# enumerate

for index,i in np.ndenumerate(arr):
    print(index,i)

1
2
3
4
5
10
20
30
40
50
1
2
3
4
5
10
20
30
40
50
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 10
(0, 1, 1) 20
(0, 1, 2) 30
(0, 1, 3) 40
(0, 1, 4) 50
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 0, 3) 4
(1, 0, 4) 5
(1, 1, 0) 10
(1, 1, 1) 20
(1, 1, 2) 30
(1, 1, 3) 40
(1, 1, 4) 50
