In [2]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [3]:
v=np.array([1,2,3],dtype='b')
print(arr)

print(v.dtype)


[1 2 3 4]
int8


In [4]:
arr=np.array(['Sumit','Nitin','Ranu'])
print(arr.dtype)

<U5


In [5]:
# (5,3,8)



import numpy as np


arr=np.arange(120).reshape(5,3,8)
print(arr)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]]

 [[ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53  54  55]
  [ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]]

 [[ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]]

 [[ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]
  [112 113 114 115 116 117 118 119]]]


# Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [6]:
import numpy as np

arr=np.array([1.2,2.2,2.4,5.1])
print(arr.dtype)

converted=arr.astype(int)
print(converted)

arr=np.array([1,2,3,4,0])
booleans=arr.astype(bool)
print(booleans)

float64
[1 2 2 5]
[ True  True  True  True False]


# NumPy Array Shape

The shape of an array is the number of elements in each dimension.

Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [8]:
import numpy as np

ar =np. array([[1,2,3,4,5,6]])
print(ar.shape)

(1, 6)


In [9]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]]).reshape(1,3,2)
print(arr)


[[[1 2]
  [3 4]
  [5 6]]]


In [10]:
arr=np.array([1,2,3,4],ndmin=3)
print(arr.shape)
print(arr)


# the example above returns (2, 3), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 3.

(1, 1, 4)
[[[1 2 3 4]]]


In [20]:
ar = np.arange(16).reshape(-1,2)
ar

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [11]:
import numpy as np

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print(arr.shape)

# matlab:2 blocks har block me 2 rows har row me 2 eleents

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


# ->Genral Rule:

->Shape ek tuple hota hai->(dim1,dim2,dim3,.....)

->ndim array ke dimensions count krta hai.

->size total elements batata hai (shape ke sab dimensions ka product)

# NumPy Array Reshaping

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension without changing data.


In [29]:
arr = np.arange(16).reshape(4,4)

arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
# Reshape From 1-D to 2-D


import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(6,-1)
print(new_arr)


arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,-1)
print(new_arr)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[1 2 3]
 [4 5 6]]


In [14]:
# Reshape From 1-D to 3-D

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(2,3,-1)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


<!-- Rules for reshape() -->

1.Total elements same hone chahaiye.
Ex:(2,3)->6 elements, isko (3,2) ya (6,) me change kar sakte ho, lekin (4,4) me nahi (16 elements required).

2.Reshape data ko copy nahi karta (mostly view deta hai).
Matlab agar reshaped array change karo,to original bhi change hoskta hai.

3.-1 ka use agar ek dimension specify na karna ho, to -1 use karte hai,NumPy automatically calculate karega.

# Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [15]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8])
new_arr=arr.reshape(2,-1)
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]]


# Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [15]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8])
new_arr=arr.reshape(2,2,-1)
print(new_arr)


# Note: We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
# import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
new_arr=arr.reshape(-1)
print(new_arr)

# 1.shape kya hai?

->shape ek tuple deta hai jo array ke dimensions(rows*cols) batata hai.

->basically array ka structure (kitane axis hai or har axis ki length kitani hai).

In [17]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6]])

print(arr.shape) #(2,3)->2 rows 3 columns

# matalb 
# axis-0(rows)=2
# axis-1(cols)=3

(2, 3)


In [18]:
# 1D array case

a=np.array([1,2,3,4])
print(a.shape) #(4,)->sirf ek dimension hai(length 4).

#3D array case

b=np.arange(24).reshape(2,3,4)
print(b) #(2,3,4)


# matlab:2 blocks, har block me 3 rows, har row me 4 elements.

(4,)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# 2.reshape kya krta hai?

->Array ka strucutre change krta hai bina elements cchange kiye.

->sirf view banata hai(kabhi kabhi copy bhi).

->Total elements same rehne chahaiye(product of dimensions constant).

In [19]:
a=np.arange(6)

b=a.reshape(2,3)
print(b.shape)

(2, 3)


# 3.Important rules of reshape.

Rule-1: Product same hona chahiye.

In [20]:
import numpy as np

arr=np.arange(12) #size 12
print(arr.reshape(3,4)) #valid (3*4=12)
print(arr.reshape(2,6)) #valid (2*6=12)

print(arr.reshape(5,5)) #error (25=!12)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


ValueError: cannot reshape array of size 12 into shape (5,5)

Rule-2: -1 use kar sakte ho auto calculate krne ke liye.

In [21]:
arr=np.arange(12)

print(arr.reshape(3,-1)) #(3,4)
print(arr.reshape(-1,6)) #(2,6)

# matlab ek dimension automatic calculate hoga.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Rule-3: reshape mostly view return krta hai,par kabhi copy bhi ho sakta hai.

In [24]:
arr=np.arange(6)
reshaped=arr.reshape(2,3)
reshaped[0,0]=99

print(reshaped) #[99 1 2 3 4 5] (view hai, original badal gaya)

[[99  1  2]
 [ 3  4  5]]


4. reshape ke real tricks

(A) Flatten karna (1D banado)

In [38]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
# print(arr.reshape(-1))

# arr.ravel()

# arr.flatten()

# print(d1)
# print(arr)
# print(arr.ravel())


arr1d=np.array([1,2,3,4,5,6])

arr1d.resize(2,5)
print(arr1d)


[[1 2 3 4 5]
 [6 0 0 0 0]]


(B)Convert 1D-> Matrix form

In [39]:
arr=np.arange(12)
print(arr.reshape(3,4)) #3rows.4cols

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(C) High dimensional reshaping

In [40]:
arr=np.arange(24)
print(arr.reshape(2,3,4)) #2blocks ,each 3*4

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# 5. Shape manipulation ke related functions

(A) ravel()->flatten(returns view mostly)

->flatten() jaisa hi hai lekin mostly view deta hai,copy nahi

->matlab agar ravel() ka result modify karogey to original bhi change ho sakta hai.

In [41]:
arr=np.arange(6).reshape(2,3)
print(arr.ravel()) #[0,1,2,3,4,5]

[0 1 2 3 4 5]


(B) flatten()->flatten(always copy)


array ko copy krke 1D bana deta hai

In [43]:
arr=np.arange(6).reshape(2,3)
flat=arr.flatten()
print(flat)
print(arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


(C) resize():

ye reshape() jaisa hi hai lekin array ko modify (in-place) krta hai.

agar elements kam pad jaaye to repeat kar deta hai ,or jyada ho to truncate kar deta hai.

In [47]:
arr=np.arange(6)
arr.resize(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


(D)size

->Total elements count krta hai(shape ke dimension ka product)


In [48]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr.size)

6


(E)np.newaxis

->Dimension increase karne ke liye use hota hai(reshape ke alternative jaisa)

In [52]:
arr=np.array([1,2,3,4])

# print(arr[:,np.newaxis])
print(arr[:,np.newaxis].shape)

(4, 1)


In [53]:
print(arr[:,np.newaxis])

[[1]
 [2]
 [3]
 [4]]


(F)np.squeeze()

->Extra dimension (size=1) remove krne ke liye.

In [65]:
import numpy as np
arr=np.array([[[1,2,3]]])

print(arr.shape)
print(np.squeeze(arr))

(1, 1, 3)
[1 2 3]


(G)np.expand_dims()

->Dimension badhata hai(opposite of squeeze).
To add new axis(dimension) to your array at specific position.


In [31]:
arr=np.array([1,2,3])

print(np.expand_dims(arr,axis=0).shape)
print(np.expand_dims(arr,axis=1).shape)


# axis=0->new row dimension added(like 1 row,3 columns).
# axis=1->new column dimension added(like 3 rows,1 column)


(1, 3)
(3, 1)


(H)np.transpose()/.T

->array ke axis swap krta hai(rows<->columns).

In [55]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr.T)
# print(arr)

[[1 4]
 [2 5]
 [3 6]]


(D) reshape VS resize

->reshape-> new view(original untouched unless modified view)
->resize->original array hi change ho jata hai.

6.Practical Dataset wala use

->Suppose image data(MNIST digits) hota hai(60000,28,28)->60k images of 28*28 pixels.

->Neural network ko input chahaiye (60000,784)

to hum karte hai:

Data science me csv ka data load karte ho toh reshape(-1,1) bahot common hai (feature ko column vector banana hota hai.)

In [57]:
arr=np.array([10,20,30,40])
print(arr.shape) #(4,)
print(arr.reshape(-1,1)) #(4,1) column vector

(4,)
[[10]
 [20]
 [30]
 [40]]


Practice questions:-


Q-1: Create a 1D NumPy array of size 10.

->Find its shape,ndim and size.


Q-2: Make a 2D array of shape(3,4) with values from 0 to 11.

->Print its shape,ndim and size.


Q-3: Convert a 1D array of size 12 into:

->shape(3,4)

->shape(2,2,3)

->shape(6,2)


Q-4: Use -1 in reshape to automatically calculate the missing dimension. Example reshape(3,4) into (2,-1)


Q-5: Create a 2D array of shape (3,3) and:

->Flatten it into 1D using flatten()

->Convert it into 1D using ravel() and change one element.

->Check whether original array changes or not.


Q-6 Take a 1D array [1,2,3,4]

->Convert it into shape(1,4) using np.newaxis

->Convert it into shape(4,1) using np.expand_dims


Q-7: Create an array of shape(1,5,1) and remove all extra dimensions using squeeze().


Q-8: Make a 2D array of shape(2,3) and print its transpose.

->Verify shape before and after transpose.


Q-9: Create a 3D array of shape (2,3,4) and use transpose() to swap axes.

->Try arr.transpose(1,0,2) and check new shape.


Q-10: Suppose you have 100 images stored in an array with shape(100,28,28) (100 grayscale images of 28*28).

->Reshape this into (100,784) (flatten each image into 1D of 784 pixels.)

->Then again reshape one image back to (28,28)


Q-11:You have a dataset with 1000 rows (samples) and 10 features->shape(1000,10).

(a) Find its ndim,size and shape.

(b) Reshape it into (10,1000) and observe the diffrence.

(c) Extract a single feature as a 1D vector (1000,).

(d) Extract a single feature as a column vector (1000,1).


Q-12 A grayscale image has shape(28,28).

(a)Flatten it into shape(28,28).

(b)Suppose you have 500 such images->shape(500,28,28).

->Reshape it into (500,784) for ML model input.

->Take one image from the dataset and reshape it back to (28,28).


Q-13:An RGB image has shape(64,64,3)->(height,width,channels).

(a)Reshape it into (4096,3) so each pixels RGB is a row.

(b) Suppose you have 100 images->shape(100,64,64,3).

->Reshape into (100,12288) for feeding into a neural network.

->Transpose a single image into (3,64,64) (channel-first format for PyTorch).


Q-14:A dataset has shape(10000,20) (10,000 samples,20 features).

(a)Reshape it into (100,100,20)->100 batches,each with 100 samples.

(b)Select one batch(100,20) and transpose it into (20,100).


Q-15:You have daily sensor data with shape(365,24)->365 days 24 hourly readings each day.

(a)Flatten it into (8760,).

(b)Add an extra dimension to make (365,24,1) for ML input.

(c)Use sequeeze to bring it back to (365,24).


Q-16: You have stock prices with shape(30,5)->30 days, 5 companies.

(a)Extract one company's stock price as a 1D array(30,).

(b)Convert the same into a column vector (30,1).

(c)Transpose the dataset to (5,30)->stocks*days.


Q-17:You have 1000 grayscale images of shape(1000,28,28).

(a)Reshape into (1000,28,28,1)->channel-last format(Tensorflow/Keras).

(b)Reshape into (1000,1,28,28)->channel-first format(PyTorch).

(c)Squeeze back into (1000,28,28).


Q-18:You have 200 senetences,each represented by 50 words,each word embedding of 100 dimensions.

->shape(200,50,100)

(a)Flatten each sentence into (200,5000) for a bag-of-word style model.

(b)Transpose it to (200,100,50) so embeddings come before word positions.

(c)Extract one sentence and reshape into (50,100)again.

In [5]:
# Q-1: Create a 1D NumPy array of size 10.
# ->Find its shape,ndim and size.

import numpy as np

arr = np.arange(10)
print(arr)
print(arr.shape)
print(arr.size)

[0 1 2 3 4 5 6 7 8 9]
(10,)
10


In [10]:
# Q-2: Make a 2D array of shape(3,4) with values from 0 to 11.
# ->Print its shape,ndim and size.

arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
12


In [16]:
# Q-3: Convert a 1D array of size 12 into:
# ->shape(3,4)
# ->shape(2,2,3)
# ->shape(6,2)

arr = np.arange(12)
print(arr)

arr = np.arange(12).reshape(3, 4)
print(arr)

arr = np.arange(12).reshape(2,2,3)
print(arr)

arr = np.arange(12).reshape(6,2)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [18]:
# Q-4: Use -1 in reshape to automatically calculate the missing dimension. 
# Example reshape(3,4) into (2,-1)

arr = np.arange(12).reshape(3, 4)
print(arr)
print(arr.shape)

new_arr = arr.reshape(2, -1)
print(new_arr)
print(new_arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [24]:
# Q-5: Create a 2D array of shape (3,3) and:
# ->Flatten it into 1D using flatten()
# ->Convert it into 1D using ravel() and change one element.
# ->Check whether original array changes or not.

arr = np.arange(1,10).reshape(3,3)
print(arr)



flat = arr.flatten()
flat[0] = 999
print(flat)
print(arr)



rav = arr.ravel()
rav[0] = 999
print(rav)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[999   2   3   4   5   6   7   8   9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[999   2   3   4   5   6   7   8   9]
[[999   2   3]
 [  4   5   6]
 [  7   8   9]]


In [64]:
# Q-6 Take a 1D array [1,2,3,4]
# ->Convert it into shape(1,4) using np.newaxis
# ->Convert it into shape(4,1) using np.expand_dims

arr = np.array([1,2,3,4])

print(arr[np.newaxis,:].shape)

print(np.expand_dims(arr,axis=1).shape)

(1, 4)
(4, 1)


In [67]:
# Q-7: Create an array of shape(1,5,1) and remove all extra dimensions using squeeze().

arr = np.array([[[1],[2],[3],[4],[5]]])
print(arr.shape)
print(np.squeeze(arr))

(1, 5, 1)
[1 2 3 4 5]


In [2]:
# Q-8: Make a 2D array of shape(2,3) and print its transpose.
# ->Verify shape before and after transpose.

import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print(arr.shape)

print(np.transpose(arr))
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(2, 3)


In [13]:
# Q-9: Create a 3D array of shape (2,3,4) and use transpose() to swap axes.
# ->Try arr.transpose(1,0,2) and check new shape.

import numpy as np

arr = np.arange(2*3*4).reshape(2,3,4)
print(arr.shape)
print(arr)


transposed_arr = arr.transpose(1, 0, 2)
print(transposed_arr.shape)
print(transposed_arr)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [ ]:
# Q-10: Suppose you have 100 images stored in an array with shape(100,28,28) (100 grayscale images of 28*28).

# ->Reshape this into (100,784) (flatten each image into 1D of 784 pixels.)
# ->Then again reshape one image back to (28,28)



In [ ]:
# Q-11:You have a dataset with 1000 rows (samples) and 10 features->shape(1000,10).
# (a) Find its ndim,size and shape.
# (b) Reshape it into (10,1000) and observe the diffrence.
# (c) Extract a single feature as a 1D vector (1000,).
# (d) Extract a single feature as a column vector (1000,1).



In [ ]:
# Q-12 A grayscale image has shape(28,28).
# (a)Flatten it into shape(28,28).
# (b)Suppose you have 500 such images->shape(500,28,28).
# ->Reshape it into (500,784) for ML model input.
# ->Take one image from the dataset and reshape it back to (28,28).



In [ ]:

# Q-10: Suppose you have 100 images stored in an array with shape(100,28,28) (100 grayscale images of 28*28).

# ->Reshape this into (100,784) (flatten each image into 1D of 784 pixels.)

# ->Then again reshape one image back to (28,28)


import numpy as np



images=np.random.randint(0,256,(100,28,28))
print("original shape:",images.shape)



image_flat=images.reshape(100,784)
print("After flat",image_flat.shape)


single_img=image_flat[0].reshape(28,28)
print(single_img.shape)



original shape: (100, 28, 28)
After flat (100, 784)
(28, 28)


In [ ]:
# import numpy as np

# arr=np.array([1,2,3,4,5,6])

# reshaped=arr.reshape((2,3)) 
# print(reshaped)



# print(arr.shape)


# arr2d=np.array([[1,2,3],[4,5,6]])
# print(arr2d.shape)



# arr=np.array([[1,2,3,4],[5,6,7,8]])
# reshaped=arr.reshape(-1)
# print(reshaped)


# ravel







# arr=np.array([1.2,2.5,3.7,4.8],dtype='int')
# print(arr)

# arr=np.array([1.2,4.5,6.7])
# converted=arr.astype(int)
# print(converted)


# import numpy as np

# arr=np.array([1,2,3,4,5,6])

# # reshaped=arr.reshape((2,4)) 
# # print(reshaped)

# arr.resize(2,3)
# print(arr)



# (2,3,4)

# arr=np.arange(24).reshape(2,3,4)
# print(arr)


# arr=np.array([[1,2,3,4],[5,6,7,8]])




# for block in arr:
#     for row in block:
#         for col in row:
#             print(col)

# for i in np.nditer(arr):
#     print(i)


# np.ndenumerate









(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(1, 0, 0) 6
(1, 0, 1) 7
(1, 0, 2) 8
(1, 1, 0) 9
(1, 1, 1) 10
(1, 1, 2) 11


In [2]:
import numpy as np

In [8]:
arr=np.arange(12).reshape(2,2,3)
for index, i in np.ndenumerate(arr):
    print(index,i)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(1, 0, 0) 6
(1, 0, 1) 7
(1, 0, 2) 8
(1, 1, 0) 9
(1, 1, 1) 10
(1, 1, 2) 11


In [5]:
arr=np.array([[[1,2,3,4],[5,6,7,8]]])

print(arr.ravel())

[1 2 3 4 5 6 7 8]


In [6]:
# flatten

arr=np.array([[[1,2,3,4],[5,6,7,8]]])
flat=arr.flatten()
print(flat)


[1 2 3 4 5 6 7 8]


🔹 TASK SET 1: Shape & Reshape
Task 1

Create a 1D NumPy array of numbers 1 to 12 and:

Print its shape

Reshape it into (3,4)

Print the new shape

Task 2

Create a 2D array of shape (2,6) and:

Convert it into a 1D array using reshape(-1)

Print both arrays

🔹 TASK SET 2: Ravel vs Flatten
Task 3

Create this array:

[[10, 20, 30],
 [40, 50, 60]]


Convert it into 1D using ravel()

Convert it into 1D using flatten()

Print both results

Task 4

Change the first value of the ravel output and observe:

Does the original array change or not?

(👉 Students will see the difference practically)

🔹 TASK SET 3: Resize
Task 5

Create a NumPy array from 1 to 6 and:

Resize it to (2,3)

Print the array

Task 6

Resize the same array to (3,4) and observe:

What values are added?

🔹 TASK SET 4: Data Type Conversion
Task 7

Create a float array:

[2.9, 4.1, 6.8, 9.5]


Convert it to integer using astype(int)

Print both arrays

Task 8

Create an array with dtype='int' directly from float values and print it.

🔹 TASK SET 5: 3D Array & Iteration
Task 9

Create a 3D array of shape (2,2,3) using np.arange() and:

Print the full array

Print only the first block

Task 10

Using nested for-loops, print each element of the 3D array.

🔹 TASK SET 6: nditer
Task 11

Using np.nditer():

Print all elements of a 3D array in one line

Count total elements manually

🔹 TASK SET 7: ndenumerate (Index + Value)
Task 12

Using np.ndenumerate():

Print index and value like this:

Index: (0, 1, 2) Value: 5

Task 13 (Thinking Task ⭐)

From a 3D array:

Print only elements greater than 5

Also print their index positions

🔹 MINI CHALLENGE 🚀
Task 14

Create a 3D array (2,3,4) and:

Convert it into 1D

Convert it into 2D (4,6)

Print shape at each step

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

