# NumPy Joining Array:


Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

Joining means combining multiple arrays into one.

Numpy ke pass isake liye alag-alag functions hote hai.


In [34]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

concatent=np.stack((arr1,arr2),axis=1)
print(concatent)


[[1 4]
 [2 5]
 [3 6]]


# 1.Concatenate()

->sabse basic join function.

->Arrays ko exiting axis ke along join karta hai.

syntax:
np.concatenate((arr1.arr2),axis=0)

In [35]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])


arr = np.concatenate((arr1, arr2),axis=1)
print(arr)


[[1 2 3 4 5 6]]


In [36]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[3,4]])


# print(np.concatenate((a,a),axis=1)) #join rows
print(np.concatenate((a,b),axis=1)) #join columns

[[1 2 5 6]
 [3 4 3 4]]


In [37]:


arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# 2.Stack()

-Arrays ko new axis ke along join karta hai.

-Shape ek axis bada hojata hai.

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [38]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.stack((a,b),axis=1)) #stack as rows
# print(np.stack((a,b),axis=1))

# print(np.concatenate((a,b),axis=0))
# print(np.concatenate((a,b),axis=1))

[[1 4]
 [2 5]
 [3 6]]


# 3.vstack() and hstack()

shortcut functions for verticle/horizontal joining.

hstack() to stack along rows.

vstack()  to stack along columns.

In [39]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.hstack((arr1,arr2))
print(arr)

arr=np.vstack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)

dstack() to stack along height, which is the same as depth.

join arrays along depth(3rd axis)

mostly 2D arrays ko 3D banta hai.

In [40]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)



a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(np.dstack((a,b)))

[[[1 4]
  [2 5]
  [3 6]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# 5.column_stack() and row_stack()

->special case of stack.

->column_stack()->1D arrays ko column-wise join karta hai.

->row_stack()->1D Arrays ko row-wise join karta hai(same as vstack).

In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.column_stack((a,b))) #as 2 columns
print(np.row_stack((a,b))) #as 2 rows

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Real life example

# socho tum ek school data analyst ho or tumhare pass alag alag arrays me students ka data hai.


# Data-1:Student IDs

student_ids=np.array([101,102,103])

# Data-2:Their marks in maths

math_marks=np.array([88,92,79])

# Data-3:Their marks in Science

science_marks=np.array([85,90,82])



# 1.np.column_stack()->Combine columns(side by side)

# tum chahte ho har student ka ID,math or science marks ek hi table (columns) me ho.

# column_stack=np.column_stack((student_ids,math_marks,science_marks))
# print(column_stack)


# 2.np.hstack()->combine horizontally(side by side)

# ab socho tumhare pass:

# ->batch1 students ke IDs or marks ek array me hai
# ->aur unke attendence percentage alag array me hai

students=np.array([[101,88,85],
                   [102,92,90],
                   [103,79,82]])

attendence=np.array([[95],
                     [80],
                     [88]])

# result=np.hstack((students,attendence))
# print(result)


# attendence ko ek extra column ke roop me jod diya


# 3.np.vstack()->combine vertically(upar niche)

# ab socho tumhare pass term1 or term2 ke marks alag arrays me hai or tum dono ko combine krna chahte ho:


term1=np.array([[101,88,85],
                [102,92,90]])

term2=np.array([[103,79,82],
                [104,91,87]])

# result=np.vstack((term1,term2))
# print(result)


# upar term1 student niche term2 students rows stundents badh gayi



# 4.np.concatenate()->full control with axis

# concatenate se tum decide karte ho kis direction me join krna hai

# result1=np.concatenate((term1,term2),axis=0)
# # print(result1)
# # result2=np.concatenate((term1,term2),axis=1)
# print(result1)


# 5.np.stack()->naya 3d layer banana

# ab tum chahte ho dono terms ke marks ek single 3d array me ho jisme 
# layer 1=term1
# layer 2=term2

# result=np.stack((term1,term2))
# print(result)

# ab array me 3d stucture ban gaya term1 or term2 dono alag layers me hai jaise cake ke layers


# column_stack->columns me jodta hai
# hstack->side by side jodta hai
# vstack->upar-niche jodta hai
# concatenate->tum decide karo kis aixs me jode
# stack->naya diension banata hai

[[101  88  85]
 [102  92  90]
 [103  79  82]
 [104  91  87]]


# Diffrence between them

Function         Axis behaviour     

concatenate      Joins along existing axis

stack            Adds a new axis

vstack           Joins along rows(axis=0)

hstack           Joins along cols(axis=1)

dstack           Joins along depth(axis=2)

column_stack     Converts 1D->2D column join

row_stack        Same as vstack 

# Broadcasting and Joining

Sometimes arrays must be same shape to join,otherwise error ata hai


In [42]:
a=np.array([1,2])
b=np.array([3,4,5])

print(np.concatenate((a,b)))

[1 2 3 4 5]


In [47]:
import numpy as np


arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],
               [6,7,8,9,10]])


merg=np.concatenate((arr1,arr2))
print(merg)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

Practice Questions:


Q-1:Create two 1D arrays [1,2,3] and [4,5,6].

->Join them using np.concatenate.

->Join them using np.hstack.

->What is the diffrence in output?


Q-2:Given arrays:

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

->Join them row-wise using concatenate.

->Join them column-wise using concatenate.


Q-3:Create two 1D arrays and join them into a 2D column matrix using np.column_stack.


Q-4:Create arrays:

a=np.array([1,2,3])
b=np.array([4,5,6])

->Stack them using np.stack with axis=0

->Stack them using np.stack with axis=1

->Explain the diffrence in shape.


Q-5:Create a (2,2) array filled with ones and another (2,2) array filled with zeros.

->Stack them along depth using np.dstack.

->Check the shape and explain.


Q-6:Create three arrays [10,20,30],[40,50,60],[0,80,90].

->Join them using np.vstack.

->Join them using np.row_stack.

->Are the results same?


Q-7:You have two features of students:

age=np.array([18,19,20,21])
marks=np.array([85,90,78,88])

->Combine them into a 2D dataset where each row is [age,marks].


Q-8:You have 3 grayscale images of size (2,2):

R=np.array([[255,0],[0,255]]) #red channel
G=np.array([[0,255],[255,0]]) #green channel
B=np.array([[100,100],[100,100]]) #blue channel


->Combine them into a single RGB image of shape(2,2,3) using np.dstack.


Q-9:You have two 1D arrays:

city=np.array(['Delhi','Mumbai','Chennai'])
temp=np.array([30,32,35])

->Use np.column_stack to combine them so that you get:

[["Delhi",30],
["Mumbai",32],
["Chennai",35]]

In [48]:
# Q-1:Create two 1D arrays [1,2,3] and [4,5,6].
# ->Join them using np.concatenate.
# ->Join them using np.hstack.
# ->What is the diffrence in output?

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate((arr1,arr2))
print(result)

result1 = np.hstack((arr1,arr2))
print(result1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [49]:
# Q-2:Given arrays:
# a=np.array([[1,2],[3,4]]) b=np.array([[5,6],[7,8]])
# ->Join them row-wise using concatenate.
# ->Join them column-wise using concatenate.

a=np.array([[1,2],
            [3,4]]) 

b=np.array([[5,6],
            [7,8]])

row_wise = np.concatenate((a,b),axis = 0)
print(row_wise)
col_wise = np.concatenate((a,b),axis = 1)
print(col_wise)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [50]:
# Q-3:Create two 1D arrays and join them into a 2D column matrix using np.column_stack.

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.column_stack((arr1,arr2))
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
# Q-4:Create arrays:
# a=np.array([1,2,3]) b=np.array([4,5,6])
# ->Stack them using np.stack with axis=0
# ->Stack them using np.stack with axis=1
# ->Explain the diffrence in shape.

a=np.array([1,2,3]) 
b=np.array([4,5,6])

result1 = np.stack((a,b), axis=0)
print(result1)

result2 = np.stack((a,b), axis=1)
print(result2)

print(result1.shape)
print(result2.shape)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


In [52]:
# Q-5:Create a (2,2) array filled with ones and another (2,2) array filled with zeros.
# ->Stack them along depth using np.dstack.
# ->Check the shape and explain.

ones = np.ones((2,2))
zeros = np.zeros((2,2))

print(ones)
print(zeros)
print(zeros.shape)

result = np.dstack((ones,zeros))
print(result)

print(result.shape)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
(2, 2)
[[[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]]
(2, 2, 2)


In [53]:
# Q-6:Create three arrays [10,20,30],[40,50,60],[0,80,90].
# ->Join them using np.vstack.
# ->Join them using np.row_stack.
# ->Are the results same?

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
arr3 = np.array([0,80,90])

result = np.vstack((arr1, arr2, arr3))
print(result)

result1 = np.row_stack((arr1, arr2, arr3))
print(result1)

print(result.shape)
print(result1.shape)

[[10 20 30]
 [40 50 60]
 [ 0 80 90]]
[[10 20 30]
 [40 50 60]
 [ 0 80 90]]
(3, 3)
(3, 3)


In [54]:
# Q-7:You have two features of students:
# age=np.array([18,19,20,21]) marks=np.array([85,90,78,88])
# ->Combine them into a 2D dataset where each row is [age,marks].

age=np.array([18,19,20,21]) 

marks=np.array([85,90,78,88])

result = np.column_stack((age,marks))
print(result)

[[18 85]
 [19 90]
 [20 78]
 [21 88]]


In [55]:
# Q-8:You have 3 grayscale images of size (2,2):
# R=np.array([[255,0],[0,255]]) #red channel 
# G=np.array([[0,255],[255,0]]) #green channel 
# B=np.array([[100,100],[100,100]]) #blue channel
# ->Combine them into a single RGB image of shape(2,2,3) using np.dstack.

R=np.array([[255,0],[0,255]]) #red channel 
G=np.array([[0,255],[255,0]]) #green channel 
B=np.array([[100,100],[100,100]]) #blue channel

result = np.dstack((R,G,B))
print(result)
print(result.shape)

[[[255   0 100]
  [  0 255 100]]

 [[  0 255 100]
  [255   0 100]]]
(2, 2, 3)


In [56]:
# Q-9:You have two 1D arrays:
# city=np.array(['Delhi','Mumbai','Chennai']) temp=np.array([30,32,35])
# ->Use np.column_stack to combine them so that you get:
# [["Delhi",30], ["Mumbai",32], ["Chennai",35]]

city=np.array(['Delhi','Mumbai','Chennai']) 
temp=np.array([30,32,35])

result = np.column_stack((city,temp))
print(result)

[['Delhi' '30']
 ['Mumbai' '32']
 ['Chennai' '35']]


# Splitting NumPy Arrays


Split matlab array ko todna(divide karna)chhote chhote parts me.
jaise ke chocalte bar ko 3 tukdo me todte ho

Numpy me bhi hum ek bade array ko tukdo (sub-arays) me tod sakte hai

In [4]:
import numpy as np
a=np.arange(12).reshape(2,6)
print(a)

part=np.hsplit(a,2)
# print(part)
for i in part:
    print(i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[0 1 2]
 [6 7 8]]
[[ 3  4  5]
 [ 9 10 11]]


1.np.split()->Fixed equal parts me todna

In [3]:
parts=np.array_split(a,4)

for i in parts:
    print(i)

# array ko 3 equal parts me tod diya
# har part me 2-2 elements
# 6 elements /3=2 per part

# np.split tabhi kaam karega jab array exactly equally divide ho sake

[[0 1 2 3 4 5]]
[[ 6  7  8  9 10 11]]
[]
[]


2.np.array_split()->Unequal bhi divide kar sakte ho


In [2]:
parts=np.array_split(a,5)
print(parts)


# ye automatic unequal divide kar dega
# koi error nahi deta
# last part chhota bhi ho sakta hai

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([], shape=(0, 6), dtype=int32), array([], shape=(0, 6), dtype=int32), array([], shape=(0, 6), dtype=int32)]


3.np.hsplit()->Horizontal split(columns ke hisab se todta hai)

In [60]:
# print(b)


# ab isako 2 parts horizontally (side-by-side) todta hai

b=np.array([[10,20,30,40],
           [50,60,70,80]])

parts=np.hsplit(b,2)
for p in parts:
    print(p)

# column wise tod diya

# Axis=1(horizontal split->columns divide hue)


[[10 20]
 [50 60]]
[[30 40]
 [70 80]]


4.np.split()->Vertical split(rows ke hisab se todta hai)

ab same array ko vertically todta hai(upar niche)

In [61]:

b=np.array([[10,20,30,40],
            [50,60,70,80]])

parts=np.vsplit(b,2)
for p in parts:
    print(p)


# row wise tod diya Axis=0(vertically split-rows divide hue)

[[10 20 30 40]]
[[50 60 70 80]]


5.np.dsplit()->depth wise split(3d arrays ke liye)


In [5]:
c=np.array([
    [[1,2,3],
     [4,5,6]],
     
     [[7,8,9],
      [10,11,12]]
])
print(c)
print(c.shape)

# ab isako depth(3rd axis) me todte hai

parts=np.dsplit(c,3)
for p in parts:
    print(p)

    

# third axis(depth/columns of 3rd dimension)ke hisab se tod diya
# axis=2(depth split)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]
[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]]


# Axis Concept:

Axis=0 -> Rows(upar niche)  -> vsplit()
Axis=1 -> Columns(left-right)-> hsplit()
Axis=2 -> Depth(layers)->dsplit()

yad rakho:
Axis=0 verticle
Axis=1 horizontal
Axis=2 Depth       

In [6]:
# 6.Split with axis

b=np.array([[10,20,30,40],
            [50,60,70,80]])


# split columns(axis=1)

result=np.split(b,2,axis=0)
for r in result:
    print(r)


# split rows(axis=0)

# result=np.split(b,2,axis=0)
# for r in result:
#     print(r)


[[10 20 30 40]]
[[50 60 70 80]]


Practical Questions:

Q-1: You have a dataset of employee salaries(in thousands):

salaries=np.array([
    [101,45000,3],
    [102,52000,4],
    [103,58000,5],
    [104,61000,6],
    [105,70000,8],
    [106,75000,9]
])

Each row=[Employee_ID,Salary,Experience]

Task: Split this dataset vertically into 3 columns(so you get ID,Salary and Experience seperately).



Q-2: Monthly sales(in thousands) of two branches combined:

sales=np.array([
    [12,15,18,20,23,25],
    [14,17,20,22,26,30]
])

Task: Split the array horizontally into 2 equal halves.

->First half=Jan-Mar

->Second half=Apr-Jun



Q-3: You have quarterly revenue data for 3 years:

revenue=np.array([
    [100,120,130,150],
    [200,230,250,270],
    [300,320,350,380]
])

Task: Split this into 4 parts- each part represents one quarter (Q1,Q2,Q3,Q4).




Q-4: marks=np.array([
    [78,82,89,91],
    [85,87,90,93],
    [75,80,83,88],
    [92,95,97,99]
])

Each row=student
Each column=subject

Task: Split students into 2 equal groups(top half,bottom half).




Q-5: data=np.array([
    [[10,20],[30,40]],
    [[50,60],[70,80]]
])

Here Each depth represents 2 diffrent months(Jan and Feb).

Task: Split this array along depth(axis=2)->so that you get 2 arrays,one for each month.




Q-6: transactions=np.array([
    [2000,2500,3000,3500,4000,4500],
    [1800,2200,2700,3200,3700,4200]
])

Each row->Account holder
Each column->Month(Jan to Jun)

Task-1: Split into 3 parts(each part=2 months).

Task-2: Find total amount of each split part using np.sum()



Q-7: feedback=np.array([
    [4,5,3,4,2,5],
    [5,4,4,5,3,4],
    [3,4,2,3,4,5]
])

Each row=Customer
Each column=Rating given over 6 months

Task: Split ratings into first 3 months and last 3 months.

Then calculate average rating in both parts for each customer.




Q-8: You have data from 4 sensors(rows),recorded every second (10 columns).

sensor_data=np.random.randint(10,100,(4,10))


Task: 
1.Split data into 5 equal time intervals(2 seconds each).

2.Find average value in each interval.


In [11]:
# Q-1: You have a dataset of employee salaries(in thousands):
# salaries=np.array([ [101,45000,3], [102,52000,4], [103,58000,5], [104,61000,6], [105,70000,8], [106,75000,9] ])
# Each row=[Employee_ID,Salary,Experience]
# Task: Split this dataset vertically into 3 columns(so you get ID,Salary and Experience seperately).

salaries=np.array([ [101,45000,3], [102,52000,4], [103,58000,5], [104,61000,6], [105,70000,8], [106,75000,9] ])

emp_id, salary, experience = np.hsplit(salaries, 3)

print(emp_id)
print(salary)
print(experience)

[[101]
 [102]
 [103]
 [104]
 [105]
 [106]]
[[45000]
 [52000]
 [58000]
 [61000]
 [70000]
 [75000]]
[[3]
 [4]
 [5]
 [6]
 [8]
 [9]]


In [17]:
# Q-2: Monthly sales(in thousands) of two branches combined:
# sales=np.array([ [12,15,18,20,23,25], [14,17,20,22,26,30] ])
# Task: Split the array horizontally into 2 equal halves.
# ->First half=Jan-Mar
# ->Second half=Apr-Jun

sales=np.array([ [12,15,18,20,23,25], 
                 [14,17,20,22,26,30] ])

result = np.hsplit(sales,2)

for i in result:
    print(i)

[[12 15 18]
 [14 17 20]]
[[20 23 25]
 [22 26 30]]


In [19]:
# Q-3: You have quarterly revenue data for 3 years:
# revenue=np.array([ [100,120,130,150], [200,230,250,270], [300,320,350,380] ])
# Task: Split this into 4 parts- each part represents one quarter (Q1,Q2,Q3,Q4).

revenue=np.array([ [100,120,130,150], [200,230,250,270], [300,320,350,380] ])

result = np.hsplit(revenue,4)

for i in result:
    print(i)

[[100]
 [200]
 [300]]
[[120]
 [230]
 [320]]
[[130]
 [250]
 [350]]
[[150]
 [270]
 [380]]


In [20]:
# Q-4: marks=np.array([ [78,82,89,91], [85,87,90,93], [75,80,83,88], [92,95,97,99] ])
# Each row=student Each column=subject
# Task: Split students into 2 equal groups(top half,bottom half).

marks=np.array([ [78,82,89,91], 
                 [85,87,90,93], 
                 [75,80,83,88], 
                 [92,95,97,99] ])

result = np.vsplit(marks,2)

for i in result:
    print(i)

[[78 82 89 91]
 [85 87 90 93]]
[[75 80 83 88]
 [92 95 97 99]]


In [23]:
# Q-5: data=np.array([ [[10,20],[30,40]], [[50,60],[70,80]] ])
# Here Each depth represents 2 diffrent months(Jan and Feb).
# Task: Split this array along depth(axis=2)->so that you get 2 arrays,one for each month.

data=np.array([ [[10,20],
                 [30,40]], 
                [[50,60],
                 [70,80]] ])

result = np.dsplit(data,2)

for i in result:
    print(i)

[[[10]
  [30]]

 [[50]
  [70]]]
[[[20]
  [40]]

 [[60]
  [80]]]


In [29]:
# Q-6: transactions=np.array([ [2000,2500,3000,3500,4000,4500], [1800,2200,2700,3200,3700,4200] ])
# Each row->Account holder, Each column->Month(Jan to Jun)
# Task-1: Split into 3 parts(each part=2 months).
# Task-2: Find total amount of each split part using np.sum()

transactions=np.array([ [2000,2500,3000,3500,4000,4500], 
                        [1800,2200,2700,3200,3700,4200] ])

result = np.hsplit(transactions,3)

for i in result:
    print(i)
    
    
result1 = np.sum(transactions)
print(result1)

[[2000 2500]
 [1800 2200]]
[[3000 3500]
 [2700 3200]]
[[4000 4500]
 [3700 4200]]
37300


In [45]:
# Q-7: feedback=np.array([ [4,5,3,4,2,5], [5,4,4,5,3,4], [3,4,2,3,4,5] ])
# Each row=Customer, Each column=Rating given over 6 months
# Task: Split ratings into first 3 months and last 3 months.
# Then calculate average rating in both parts for each customer.

feedback=np.array([ [4,5,3,4,2,5], 
                    [5,4,4,5,3,4], 
                    [3,4,2,3,4,5] ])

result = np.hsplit(feedback,3)

for i in result:
    print(i)
    
# result = np.mean(feedback)
result = np.average(feedback)
print(result)

[[4 5]
 [5 4]
 [3 4]]
[[3 4]
 [4 5]
 [2 3]]
[[2 5]
 [3 4]
 [4 5]]
3.8333333333333335


In [42]:
# Q-8: You have data from 4 sensors(rows),recorded every second (10 columns).
# sensor_data=np.random.randint(10,100,(4,10))
# Task: 1.Split data into 5 equal time intervals(2 seconds each).
# 2.Find average value in each interval.

sensor_data=np.random.randint(10,100,(4,10))

intervals = np.hsplit(sensor_data,5)
print(intervals)

[array([[44, 50],
       [27, 27],
       [41, 80],
       [76, 35]]), array([[56, 44],
       [59, 48],
       [97, 72],
       [78, 26]]), array([[26, 25],
       [55, 45],
       [47, 43],
       [37, 64]]), array([[26, 35],
       [42, 28],
       [90, 66],
       [56, 15]]), array([[29, 94],
       [56, 10],
       [77, 41],
       [15, 87]])]


In [ ]:
import numpy as np


# arr1=np.array([[1,2,3,4],
#                [34,56,78,90]])

# arr2=np.array([[12,13,14,56],
#                [6,7,8,9]])

# result=np.concatenate((arr1,arr2),axis=1)
# print(result)



# arr1=np.array([1,2,3,4])
# arr2=np.array([4,5,6,7])

# result=np.stack((arr1,arr2),axis=1)
# print(result)

[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [ ]:
# hstack,vstack,column_stack,row_stack

# student_ids=np.array([101,102,103])

# maths_marks=np.array([56,78,98])

# science_marks=np.array([12,89,76])


# result=np.column_stack((student_ids,maths_marks,science_marks))
# print(result)


# attendence=np.array([[98],
#                      [44],
#                      [67]])


# result2=np.hstack((result,attendence))
# print(result2)



[[101  56  12]
 [102  78  89]
 [103  98  76]]
[[101  56  12  98]
 [102  78  89  44]
 [103  98  76  67]]


In [ ]:
# term1=np.array([[101,78,98],
#                 [102,56,87]])

# term2=np.array([[103,45,89],
#                 [104,56,76]])



# result=np.dstack((term1,term2))
# print(result)

[[[101 103]
  [ 78  45]
  [ 98  89]]

 [[102 104]
  [ 56  56]
  [ 87  76]]]


In [ ]:
# arr=np.array([1,2,3,4,5])

# result=np.array_split(arr,4)
# print(result)

[array([1, 2]), array([3]), array([4]), array([5])]


In [ ]:
# hsplit,vsplit,dsplit

arr=np.array([[1,2,3,4],
              [5,6,7,8]])

result=np.vsplit(arr,2)


for i in result:
    print(i)

[[1 2 3 4]]
[[5 6 7 8]]


In [30]:
arr=np.array([[[10,20,30],
               [45,67,89]],
              
              [[43,54,76],
               [23,43,45]]])

result=np.dsplit(arr,3)
for i in result:
    print(i)

[[[10]
  [45]]

 [[43]
  [23]]]
[[[20]
  [67]]

 [[54]
  [43]]]
[[[30]
  [89]]

 [[76]
  [45]]]
