# Numpy Array Searching


->Kisi array me konsa element hai
->kaha kis index par hai
->ya kaunsa condition ko satisfy krte hai ye sab find karna.

In [3]:
import numpy as np

arr=np.array([10,20,30,40,50])
result=np.where(arr%2==0)
result=np.where((arr>10) & (arr<40))
print(result)

resulted=np.searchsorted(arr,[35,23])
print(resulted)


nonzeros=np.nonzero(arr)
print(nonzeros)


arr=np.array([5,10,20,1])

print(np.any(arr==0)) #true-at least one zero
print(np.all(arr>0))


arr=np.array([50,20,30,10,40])
sorted_arr=np.sort(arr)

print("Original:",arr)
print("Sorted:",sorted_arr)


arr2d=np.array([[50,20,30],
               [10,60,40]])

# sort each row(axis=1)

np.sort(arr2d,axis=1)


arr=np.array([10,19,14,50,30])
st=np.argsort(arr)
print(st)


names=np.array(['Alice','Bob','Charlie','David',"Eva"])
marks=np.array([50,20,30,10,40])

sorted_names=names[np.argsort(marks)]
print(sorted_names)

(array([1, 2], dtype=int64),)
[3 2]
(array([0, 1, 2, 3, 4], dtype=int64),)
False
True
Original: [50 20 30 10 40]
Sorted: [10 20 30 40 50]
[0 2 1 4 3]
['David' 'Bob' 'Charlie' 'Eva' 'Alice']


In [4]:
import numpy as np

# arr=np.array([10,20,10,40,50,10])

# result=np.where(arr==10)
# print(result)


arr=np.array([10,20,30,40,50,60,70])

result=np.where((arr>10) & (arr<50))
print(result)

(array([1, 2, 3]),)


# 1.np.where() - find indexes based on condition

syntax:-np.where(condition)

ye function batata hai kis index par condition True hai.

In [1]:
import numpy as np

arr=np.array([10,20,30,40,50,60])

result=np.where(arr>30)
print(result)


arr=np.array([5,10,15,10,20,0])
result=np.where(arr==10)
print(result)

(array([3, 4, 5], dtype=int64),)
(array([1, 3], dtype=int64),)


In [4]:
# using multiple conditions
import numpy as np

arr=np.array([2,5,8,12,15,20])
result=np.where((arr>5) & (arr<15))
print(result)


# conditional replacement

# you can also use np.where() to replace values conditionally

arr=np.array([10,20,30,40,50])
new_arr=np.where(arr>30,'High','Low')
print(new_arr)

(array([2, 3], dtype=int64),)
['Low' 'Low' 'Low' 'High' 'High']


# 2.np.searchsorted()-Find where to insert

np.searchsorted(sorted_array,value)

ye function batata hai kis index par ek value insert karni chahaiye taki array sorted rahe.

In [5]:
arr=np.array([10,20,30,40,50])
x=np.searchsorted(arr,35)
print(x)


# means ->if u insert 35 at index 3 ,array remains sorted.
# result=10,20,30,35,40,50


# multiple values insert karna

arr=np.array([10,20,30,40,50])
x=np.searchsorted(arr,[25,45])
print(x)


# using side='right'
arr=np.array([10,20,30,40,50])
x=np.searchsorted(arr,30,side='left')
print(x)

# if duplicate value exist side='right' gives position after duplicates


3
[2 4]
2


In [6]:
arr=np.array([10,20,30,40,50])

sorted=np.searchsorted(arr,[25,45])
print(sorted)

[2 4]


# 3.np.nonzero()-Find non-zero elements

it gives indexes where elements is not equal to 0.

In [6]:
arr=np.array([0,2,0,4,5,0])
result=np.nonzero(arr)
print(result)

(array([1, 3, 4], dtype=int64),)


# 4.Boolean indexing (direct searching)

you can directly use boolean conditions to get elements.

In [7]:
arr=np.array([10,25,30,45,60])
print(arr[arr>30])

# it directly returns elemetns greater than 30

[45 60]


# 5.np.any() and np.all() for checking conditions

In [13]:
# np.any()->checks if any element matches condition.

# np.all()->checks if all elements match condition.

arr=np.array([5,10,20,1,0])

print(np.any(arr==0)) #true-at least one zero
print(np.all(arr>0)) #false -beacuse 0 is not >0

True
False


Dataset 1 — Students Marks

marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

Q11: Find indexes of students who passed (marks ≥ 50).

Q12: Replace all marks below 50 with 0 using np.where().

Q13: Find where a new score 75 should be inserted to keep marks sorted.

Q14: Get all scores greater than average marks.



🧩 Dataset 2 — Product Prices

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])

Q15: Find positions of products cheaper than ₹1000.

Q16: Replace prices above ₹2000 with 'Expensive', others with 'Affordable'.

Q17: Using np.searchsorted(), find where ₹1600 should be inserted to maintain order.

Q18: Get all product prices between ₹1000 and ₹2000 using boolean indexing.




🧩 Dataset 3 — City Temperatures (°C)

temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])

Q19: Find indexes of days where temperature > 35°C.

Q20: Replace all temps > 35°C with 'Hot' and others with 'Normal'.

Q21: Find where to insert a new temperature reading 33 to keep sorted order.

Q22: Get all temperatures below average temperature.




🧩 Dataset 4 — Employee Salaries

salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])

Q23: Find indexes of employees earning more than ₹40,000.

Q24: Replace salaries below ₹30,000 with 'Low', others with 'High'.

Q25: Find where a new salary ₹50000 should be inserted in the sorted salary list.

Q26: Get all salaries above the company average.




🧩 Dataset 5 — Daily Steps (Fitness Tracker)

steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

Q27: Find indexes of days with steps > 8000.

Q28: Replace steps below 5000 with 'Low Activity' and others with 'Active'.

Q29: Get all days where steps are below the weekly average.

Q30: Check using np.any() if any day has 0 steps (missed logging).




# 🧩 Dataset 1 — Students Marks

In [15]:
# Q11: Find indexes of students who passed (marks ≥ 50).

marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

result = np.where(marks>= 50)

print(result)

(array([1, 2, 3, 5, 6, 7], dtype=int64),)


In [16]:
# Q12: Replace all marks below 50 with 0 using np.where().

marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

result = np.where(marks<50)
print(result)

(array([0, 4], dtype=int64),)


In [11]:
# Q13: Find where a new score 75 should be inserted to keep marks sorted.

marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

result = np.sort(marks)

result1 = np.searchsorted(result1,75)

print(result)
print(result1)


[35 40 50 55 65 70 80 90]
6


In [33]:
# Q14: Get all scores greater than average marks.
   
marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

avg = marks.mean()

result = marks[marks>avg]

print(avg)
print(result)

60.625
[65 80 90 70]


# 🧩 Dataset 2 — Product Prices

In [34]:
# Q15: Find positions of products cheaper than ₹1000.

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])

cheaper = np.where(prices < 1000)

print(cheaper)

(array([1, 5], dtype=int64),)


In [36]:
# Q16: Replace prices above ₹2000 with 'Expensive', others with 'Affordable'.

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])

result = np.where(prices > 2000, 'Expensive','Affordable')
print(result)

['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Affordable' 'Expensive']


In [5]:
# Q17: Using np.searchsorted(), find where ₹1600 should be inserted to maintain order.

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])
           
sorted_price = np.sort(prices)
result = np.searchsorted(sorted_price, 1600)

print(sorted_price)
print(result)

[ 800  900 1200 1500 1800 2500 3000]
4


In [6]:
# Q18: Get all product prices between ₹1000 and ₹2000 using boolean indexing.

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])

result = prices[(prices >= 1000) & (prices<=2000)]

print(result)

[1200 1500 1800]


# 🧩 Dataset 3 — City Temperatures (°C)

In [7]:
# Q19: Find indexes of days where temperature > 35°C.

temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])

result = np.where(temps> 35)

print(result)

(array([2, 5, 7], dtype=int64),)


In [8]:
# Q20: Replace all temps > 35°C with 'Hot' and others with 'Normal'.

temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])

result = np.where(temps> 35, 'Hot', 'Normal')
print(result)

['Normal' 'Normal' 'Hot' 'Normal' 'Normal' 'Hot' 'Normal' 'Hot']


In [16]:
# Q21: Find where to insert a new temperature reading 33 to keep sorted order.

temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])

sorted_temps = np.sort(temps)
print(sorted_temps)

result = np.searchsorted(sorted_temps,33)
print(result)

[25 28 29 31 34 38 40 41]
4


In [18]:
# Q22: Get all temperatures below average temperature.

temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])

avg = temps.mean()
print(avg)

result = temps[temps<avg]
print(result)

33.25
[28 25 31 29]


# 🧩 Dataset 4 — Employee Salaries

In [19]:
# Q23: Find indexes of employees earning more than ₹40,000.
    
salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])

result = np.where(salaries > 40000)
print(result)

(array([2, 4, 5], dtype=int64),)


In [4]:
# Q24: Replace salaries below ₹30,000 with 'Low', others with 'High'.

salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])

result = np.where(salaries <30000, 'Low','High')
print(result)

['Low' 'High' 'High' 'Low' 'High' 'High' 'High']


In [5]:
# Q25: Find where a new salary ₹50000 should be inserted in the sorted salary list.

salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])


result = np.sort(salaries)
print(result)

[25000 28000 32000 35000 45000 60000 75000]


In [9]:
# Q26: Get all salaries above the company average.

import numpy as np
salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])

avg = np.mean(salaries)
result1 = salaries[salaries>avg]

print(result)
print(result1)

42857.142857142855
[45000 60000 75000]


# 🧩 Dataset 5 — Daily Steps (Fitness Tracker)

In [13]:
# Q27: Find indexes of days with steps > 8000.
    
steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

result = np.where(steps>8000)

for i in result:
    print(i)

[2 4]


In [15]:
# Q28: Replace steps below 5000 with 'Low Activity' and others with 'Active'.

steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

result = np.where(steps<5000, 'Low Activity', 'Active')

for i in result:
    print(i)

Low Activity
Active
Active
Low Activity
Active
Active
Active


In [18]:
# Q29: Get all days where steps are below the weekly average.

steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

weekly_avg  = steps.mean()

below_avg_days = steps[steps < weekly_avg]

print(weekly_avg)
print(below_avg_days)

7214.285714285715
[4000 3000 6000]


In [23]:
# Q30: Check using np.any() if any day has 0 steps (missed logging).

steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

result = np.any(steps==0)

print(result)

False


# Numpy Array Sorting

array ke elements ko ascending ya descending order me arrange karna.

Numpy me ye kaam hum np.sort(),sort method or argsort() se krte hai.

np.sort()->Returns a sorted copy


np.sort(array,axis=-1,kind='quicksort',order=None)

array->input array
axis->along which axis to sort (-1=last axis by default)
kind->sorting algorithm(quicksort,mergesort,heapsort)
order->only for strucutred arrays

np.sort() returns a new sorted array,original array unchanged.

In [8]:
import numpy as np

arr=np.array([50,20,30,10,40])
sorted_arr=np.sort(arr)

print("Original:",arr)
print("Sorted:",sorted_arr)


# Descending order

arr=np.array([50,20,30,10,40])
sorted_arr=np.sort(arr)[::-1]
print(sorted_arr)

Original: [50 20 30 10 40]
Sorted: [10 20 30 40 50]
[50 40 30 20 10]


2.array.sort()->sort in-place

array.sort(axis=-1,kind='quicksort',order=None)

->array.sort() modifies the original array (in-place)

->does not return a new array

In [13]:
arr=np.array([50,20,30,10,40])
arr.sort()
print(arr)

# original array sorted in-place

[10 20 30 40 50]


3.Sorting 2D arrays-axis parameter


axis=0->sort each column

axis=1->sort each row

In [9]:
import numpy as np

arr2d=np.array([[50,20,30],
               [10,60,40]])

# sort each row(axis=1)

np.sort(arr2d,axis=1)


# sort each column(axis=0)

# np.sort(arr2d,axis=0)

array([[20, 30, 50],
       [10, 40, 60]])

In [10]:
arr=np.array([10,19,14,50,30])


st=np.argsort(arr)
print(st)

[0 2 1 4 3]


4.argsort()-get indexes instead of values

np.argsort(array)->returns indexes that would sort the array

useful for tracking original positions.

In [12]:
arr=np.array([50,20,30,10,40])
indices=np.argsort(arr)
print(indices)

# at index 3->10(smallest)

# ar index 1->20

# at index 0->50

# using these indexes you can reorder thr array other related arrays


# using argsort to sort another array

names=np.array(['Alice','Bob','Charlie','David',"Eva"])
marks=np.array([50,20,30,10,40])

sorted_names=names[np.argsort(marks)]
print(sorted_names)

# sorted by marks names follow the same order 

[3 1 2 4 0]
['David' 'Bob' 'Charlie' 'Eva' 'Alice']


# Practice Questions


Q1:

Array of numbers:

arr = np.array([50, 20, 30, 10, 40])

Sort the array in ascending order using np.sort().

Sort the array in descending order.





Q2:

Array of marks:

marks = np.array([55, 70, 40, 90, 65])

Sort the marks in-place using sort() method.





Q3:

2D array of scores:

scores = np.array([[50, 20, 30],
                   [10, 60, 40]])

Sort each row.

Sort each column.





Q4:

Array with duplicate values:

arr = np.array([50, 20, 50, 10, 40])

Sort the array using mergesort to maintain stability.




🔹 Part 2: Real Dataset Style Sorting Questions

Dataset 1 — Students Marks

names = np.array(["Alice", "Bob", "Charlie", "David", "Eva"])
marks = np.array([50, 20, 30, 10, 40])

Q5:

Sort marks in ascending order.

Sort names according to marks using argsort().


Q6:

Sort only students who scored >20, both marks and names.





Dataset 2 — Employee Salaries

employees = np.array(["John", "Sara", "Mike", "Anna", "David"])
salaries = np.array([45000, 35000, 50000, 30000, 40000])

Q7:

Sort salaries in ascending order.

Sort employees according to salaries using argsort().


Q8:

Find employees earning more than 40000, sort them ascendingly, and print both names and salaries.




Dataset 3 — Product Prices

products = np.array(["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"])
prices = np.array([75000, 35000, 45000, 15000, 5000])

Q9:

Sort prices in ascending order.

Sort products according to prices using argsort().


Q10:

Sort only products costing more than 20000, both names and prices.





Dataset 4 — City Temperatures (°C)

cities = np.array(["Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore"])
temps = np.array([40, 35, 38, 37, 30])

Q11:

Sort temps ascending.

Sort cities according to temperatures using argsort().


Q12:

Find cities with temperature > 35°C and sort them ascendingly by temperature.





Dataset 5 — Daily Sales (Units)

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri"])
sales = np.array([200, 450, 300, 500, 150])

Q13:

Sort sales in ascending order.

Sort days according to sales using argsort().


Q14:

Find days where sales > 250, and sort them ascendingly by sales.

In [25]:
# Q1: Array of numbers:
# arr = np.array([50, 20, 30, 10, 40])
# Sort the array in ascending order using np.sort().
# Sort the array in descending order.

arr = np.array([50, 20, 30, 10, 40])

ascending = np.sort(arr)

descending = np.sort(arr)[::-1]


print(ascending)
print(descending)

[10 20 30 40 50]
[50 40 30 20 10]


In [26]:
# Q2: Array of marks:
# marks = np.array([55, 70, 40, 90, 65])
# Sort the marks in-place using sort() method.

marks = np.array([55, 70, 40, 90, 65])

result = np.sort(marks)

print(result)

[40 55 65 70 90]


In [28]:
# Q3: 2D array of scores:
# scores = np.array([[50, 20, 30], [10, 60, 40]])
# Sort each row.
# Sort each column.

scores = np.array([[50, 20, 30], [10, 60, 40]])

row_wise = np.sort(scores, axis = 0)
print(row_wise)

col_wise = np.sort(scores, axis = 1)
print(col_wise)

[[10 20 30]
 [50 60 40]]
[[20 30 50]
 [10 40 60]]


In [30]:
# Q4: Array with duplicate values:
# arr = np.array([50, 20, 50, 10, 40])
# Sort the array using mergesort to maintain stability.

arr = np.array([50, 20, 50, 10, 40])

result = np.sort(arr,kind = 'mergesort')

print(result)

[10 20 40 50 50]


# 🔹 Part 2: Real Dataset Style Sorting Questions

Dataset 1 — Students Marks

In [41]:
# Q5: Sort marks in ascending order.
# Sort names according to marks using argsort().

names = np.array(["Alice", "Bob", "Charlie", "David", "Eva"]) 
marks = np.array([50, 20, 30, 10, 40])


sorted_marks =  np.sort(marks)
result = names[np.argsort(marks)]
print(sorted_marks)
print(result)

[10 20 30 40 50]
['David' 'Bob' 'Charlie' 'Eva' 'Alice']


In [45]:
# Q6: Sort only students who scored >20, both marks and names.
    
names = np.array(["Alice", "Bob", "Charlie", "David", "Eva"]) 
marks = np.array([50, 20, 30, 10, 40])

index = np.argsort(marks[marks>20])

print(names [ marks > 20 ][index])
print(marks [ marks >20 ][index])

['Charlie' 'Eva' 'Alice']
[30 40 50]


Dataset 2 — Employee Salaries

In [49]:
# Q7: Sort salaries in ascending order.
# Sort employees according to salaries using argsort().

employees = np.array(["John", "Sara", "Mike", "Anna", "David"]) 
salaries = np.array([45000, 35000, 50000, 30000, 40000])

sort_salary = np.sort(salaries)
print(sort_salary)

sort_employee = employees[np.argsort(salaries)]
print(sort_employee)



[30000 35000 40000 45000 50000]
['Anna' 'Sara' 'David' 'John' 'Mike']


In [50]:
# Q8: Find employees earning more than 40000, sort them ascendingly, and print both names and salaries.

employees = np.array(["John", "Sara", "Mike", "Anna", "David"]) 
salaries = np.array([45000, 35000, 50000, 30000, 40000])

idx = np.argsort(salaries[salaries > 40000])

print(employees[salaries > 40000][idx])
print(salaries[salaries > 40000][idx])

['John' 'Mike']
[45000 50000]


In [53]:
# Q9: Sort prices in ascending order.
# Sort products according to prices using argsort().

products = np.array(["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"]) 
prices = np.array([75000, 35000, 45000, 15000, 5000])

asce = np.sort(prices)
print(asce)

result = products[np.argsort(prices)]

print(result)

[ 5000 15000 35000 45000 75000]
['Keyboard' 'Monitor' 'Phone' 'Tablet' 'Laptop']


In [57]:
# Q10: Sort only products costing more than 20000, both names and prices.

products = np.array(["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"]) 
prices = np.array([75000, 35000, 45000, 15000, 5000])

cost = np.argsort(prices[prices>20000])

print(cost)

print(products[prices>20000][cost])
print(prices[prices>20000][cost])

[1 2 0]
['Phone' 'Tablet' 'Laptop']
[35000 45000 75000]


# Dataset 4 — City Temperatures (°C)

In [60]:
# Q11: Sort temps ascending.
# Sort cities according to temperatures using argsort().

cities = np.array(["Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore"]) 
temps = np.array([40, 35, 38, 37, 30])

sort_temp = np.sort(temps)
print(sort_temp)

sort_cities = cities[np.argsort(temps)]
print(sort_cities)

[30 35 37 38 40]
['Bangalore' 'Mumbai' 'Chennai' 'Kolkata' 'Delhi']


In [14]:
# Q12: Find cities with temperature > 35°C and sort them ascendingly by temperature.

cities = np.array(["Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore"]) 
temps = np.array([40, 35, 38, 37, 30])

sort_temp = temps[temps>35]
print(sort_temp)

result = cities[np.argsort(sort_temp)]
print(result)


# sort_temp = np.sort(temps)
# city_with_temp = np.argsort(temps[temps>35])

# # city_with_temp = cities[np.argsort(temps>35)]

# print(sort_temp)
# print(city_with_temp)

[40 38 37]
['Kolkata' 'Mumbai' 'Delhi']


# Dataset 5 — Daily Sales (Units)

In [69]:
# Q13: Sort sales in ascending order. Sort days according to sales using argsort().

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri"]) 
sales = np.array([200, 450, 300, 500, 150])

sort_sale = np.sort(sales)
print(sort_sale)

sort_day = days[np.argsort(sales)]
print(sort_day)

[150 200 300 450 500]
['Fri' 'Mon' 'Wed' 'Tue' 'Thu']


In [17]:
# Q14: Find days where sales > 250, and sort them ascendingly by sales.
    
import numpy as np 

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri"]) 
sales = np.array([200, 450, 300, 500, 150])

ss=sales[sales>250]
print(ss)

result=days[np.argsort(ss)]
print(result)

[450 300 500]
['Tue' 'Mon' 'Wed']


In [35]:
import numpy as np

# where


# arr=np.array([10,20,30,40,50,60])
# result=np.where(arr>30,'high','low')
# print(result)


# searchsorted

arr=np.array([10,20,30,40,50])
insert=np.searchsorted(arr,[25,54])
# print(insert)


# nonzero

arr=np.array([0,0,0,1,2,3,4,5,0,0])
non=np.nonzero(arr)
# print(non)



# any
# all

# arr=np.array([0,0])
# print(np.any(arr==0))
# result


# arr=np.array([100,10,22,34,76,89])
# result=np.sort(arr)[::-1]
# print(result)


# arr=np.array([[10,12,14,50],
#               [2,40,56,32]])


# print(np.sort(arr,axis=1))


# argsort

# arr=np.array([10,50,40,20])
# re=np.argsort(arr)
# print(re)
;;;;;;;;;x
import numpy as np

names=np.array(['Bhargav','Jaydeep','Zala','Akshit'])
marks=np.array([98,67,56,100])


result=names[np.argsort(marks)]
print(result)




['Zala' 'Jaydeep' 'Bhargav' 'Akshit']
