# NumPy Random

numpy.random module random numbers generate karne ke liye use hota hai.
ye kaam ata hai data simulation,sampling,shuffling,testing ML models etc.


In [2]:
import numpy as np

arr=np.random.randn(2,3)
print(arr)

[[-0.88428626  0.6665266   1.30535404]
 [ 0.22102072 -0.41394345  0.72665879]]


In [15]:
import numpy as np

# arr=np.random.randn(2,3,4)
# print(arr)


arr=np.array([2,3,4,5,6])

print(np.random.choice(arr,5))

[6 2 5 5 6]


# 1.Random Float Numbers

np.random.rand()->Uniform Distribution (0 to 1)

In [4]:
import numpy as np

# arr=np.random.rand(5) #5 random numbers between 0 to 1
# print(arr)


# explanation:

# ->Generate uniformly distributed float numbers between 0 and 1.a

# ->Can specify shape for multi-dimensional arrys.

arr2d=np.random.rand(2,3) #2 rows and 3 columns
print(arr2d)

[[0.6760766  0.8486598  0.07498636]
 [0.52092737 0.51575454 0.40179368]]


In [6]:
import numpy as np

arr=np.random.rand(5)
# print(arr)

arr1=np.random.rand(4,5)
# print(arr1)

arr2=np.random.rand(8,2,3)
# print(arr2)

arr3=np.random.rand(10,20,40)
print(arr3)


# arr=np.random.randint(1,5,size=10)
# print(arr)

# arr=np.random.randint(1,10,size=12)
# print(arr)

[[[0.85857326 0.21207702 0.00535603 ... 0.59952649 0.64096255 0.98606941]
  [0.10089811 0.55885111 0.99137815 ... 0.44452331 0.03217413 0.78199917]
  [0.39078752 0.16042391 0.55681201 ... 0.8812367  0.58100924 0.6542734 ]
  ...
  [0.73602907 0.13793361 0.96337849 ... 0.06797858 0.87538251 0.0869915 ]
  [0.08722594 0.57965149 0.79729668 ... 0.62584934 0.06564737 0.95440162]
  [0.73872554 0.19103855 0.25009229 ... 0.745157   0.03381401 0.97163978]]

 [[0.7885823  0.52555336 0.57047517 ... 0.67955642 0.40241878 0.19047444]
  [0.53754957 0.10309994 0.55394184 ... 0.46777531 0.94424787 0.72321546]
  [0.71387692 0.97159821 0.22676723 ... 0.70229427 0.95913408 0.55794035]
  ...
  [0.02374604 0.68135169 0.31461252 ... 0.83970493 0.27233907 0.17326715]
  [0.87717882 0.68633347 0.86334589 ... 0.51192399 0.61538627 0.93771066]
  [0.07256956 0.61673553 0.42114703 ... 0.19274639 0.99620153 0.12037579]]

 [[0.62094578 0.37319011 0.96529069 ... 0.69361159 0.70588584 0.17267357]
  [0.58293031 0.232454

# 2.Random Integers

np.random.randint()->Random Integers

In [ ]:
arr=np.random.randint(10,50,size=5)
print(arr)

# 10,50->range(10 inclusive,50 exclusive)
# size=5->number of elements

# multi-dimensional

arr2d=np.random.randint(1,10,size=(3,4))
print(arr2d)
arr3d=np.random.randint(10,50,size=11)
print(arr3d)
arr4d=np.random.randint(11,15,size=10)
print(arr4d.size)
print(arr3d.shape)

arr=np.array([[[10,20,30],[40,50,60]]
              ,[[89,56,45],[101,102,103]]
              ,[[45,67,89],[34,52,23]]])



print(arr.ndim)

splitting=np.split()

[18 23 42 10 38]
[[9 2 8 1]
 [5 7 7 7]
 [8 2 6 6]]
[10 18 10 14 14 17 34 40 37 10 10]
10
(11,)
3


# 3.Random normal distribution

np.random.randn()->Standard normal distribution


In [9]:
arr=np.random.randn(5)
print(arr)

# mean=0,standard deviation=1

# can create 2D arrays:
np.random.randn(2,3)

[-1.14168025  0.70233874  1.53645209  0.94688624 -0.87856505]


array([[-0.09401551,  0.02326805,  0.39728113],
       [-1.90165984, -0.34987235,  0.56887924]])

# 4.Random Choice

np.random.choice()-pick random elements from array


In [8]:

# arr=np.array([10,20,30,40,50])
# rand_pick=np.random.choice(arr,size=4)
# print(rand_pick)

# replace=False->without repetition
# replace=True->with repetition

np.random.seed(12)
print(np.random.randint(10,20,size=2))


[16 11]


# 5.Shuffle Array

np.random.shuffle()->shuffle in-place

In [9]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

# changes original array

[2 5 1 4 3]


# 6.Random Seed

np.random.seed()-Make results reproducible


In [10]:
np.random.seed(100)
print(np.random.randint(1,5,size=2))


# seed ensures same random numbers every run

# useful for debugging & testing models


[1 1]


Practice Questions


Q1.

Generate an array of 5 random float numbers between 0 and 1 using np.random.rand().




Q2.

Create a 2D random array (shape = 3x4) with random numbers between 0 and 1.




Q3.

Generate 10 random integers between 50 and 100 using np.random.randint().




Q4.

Create a 3x3 matrix of random integers between 1 and 9.




Q5.

Generate 5 random numbers from a normal distribution using np.random.randn().




Q6.

Use np.random.choice() to select 3 random elements from the array:

arr = np.array([10, 20, 30, 40, 50])




Q7.

Use np.random.choice() to pick 5 elements with replacement from:

arr = np.array([1, 2, 3, 4, 5])




Q8.

Shuffle this array using np.random.shuffle():

arr = np.array([1, 2, 3, 4, 5])




Q9.

Generate two random arrays using the same np.random.seed(10) —
check if both give the same result.




Q10.

Generate a 4x4 matrix of random integers between 10 and 99 and find:

Maximum value

Minimum value

Mean







Q11. Student Marks Simulation 

Simulate marks (0–100) of 15 students using np.random.randint()

Find the top 5 marks (sorted descending).

Randomly select 3 students for a prize.





Q12. Daily Sales Data 

Generate daily sales for 7 days between 200 and 1000 units.

Find the day with the highest sales.

Randomly pick 2 days for a special offer.

Shuffle the sales data.





Q13. Employee Salary Data 

Create salary data for 8 employees between 30,000 and 80,000.

Find the employee with the lowest salary.

Randomly pick 2 employees for a bonus.





Q14. Product Prices 

You have 10 products. Generate random prices between ₹100 and ₹1000.

Sort the prices in ascending order.

Pick 3 random products for a discount.





Q15. Weather Temperature Data 

Simulate 10 random daily temperatures between 25°C and 45°C.

Find 3 hottest days using argsort().

Randomly shuffle the temperature data.





Q16. Exam Simulation 

You are simulating marks of 1000 students (0–100).

Find the average mark.

Find how many scored above 80.

Randomly select 10 for interview.





Q17. Random Sampling in Population 

Create an array representing 1000 people IDs (1–1000).

Randomly select 50 people for a survey (no repetition).

Randomly select 5 people for a prize (with repetition).





Q18. Game Simulation 

A dice game is played 10 times.

Simulate the results using np.random.randint(1, 7, 10).

Find how many times 6 appeared.

In [11]:
# Q1. Generate an array of 5 random float numbers between 0 and 1 using np.random.rand().

arr = np.random.rand(5)
print(arr)

[0.27836939 0.42451759 0.84477613 0.00471886 0.12156912]


In [12]:
# Q2. Create a 2D random array (shape = 3x4) with random numbers between 0 and 1.

arr = np.random.rand(3,4)

print(arr)

[[0.67074908 0.82585276 0.13670659 0.57509333]
 [0.89132195 0.20920212 0.18532822 0.10837689]
 [0.21969749 0.97862378 0.81168315 0.17194101]]


In [13]:
# Q3. Generate 10 random integers between 50 and 100 using np.random.randint().

arr = np.random.randint(50,100, size = 10)

print(arr)

[69 86 54 77 53 57 99 97 51 64]


In [4]:
# Q4. Create a 3x3 matrix of random integers between 1 and 9.

arr = np.random.randint(1,10, size = (3,3))

print(arr)

[[9 8 7]
 [2 2 8]
 [5 8 6]]


In [5]:
# Q5. Generate 5 random numbers from a normal distribution using np.random.randn().

arr = np.random.randn(5)

print(arr)

[ 0.34801623  1.1426297   0.15572158  0.13715403 -0.94395031]


In [8]:
# Q6. Use np.random.choice() to select 3 random elements from the array:

arr = np.array([10, 20, 30, 40, 50])
               
rand_pick = np.random.choice(arr, size = 3)
               
print(rand_pick)

[20 10 20]


In [9]:
# Q7. Use np.random.choice() to pick 5 elements with replacement from:
# arr = np.array([1, 2, 3, 4, 5])

arr = np.array([1, 2, 3, 4, 5])

result = np.random.choice(arr, size=5, replace=True)
print(result)

[5 2 2 5 3]


In [8]:
# Q8. Shuffle this array using np.random.shuffle():
# arr = np.array([1, 2, 3, 4, 5])

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

print(arr)

[2 1 3 5 4]


In [10]:
# Q9. Generate two random arrays using the same np.random.seed(10)
# check if both give the same result.

np.random.seed(10)
arr1 = np.random.rand(5)
print(arr1)

np.random.seed(10)
arr2 = np.random.rand(5)
print(arr2)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


In [11]:
# Q10. Generate a 4x4 matrix of random integers between 10 and 99 and find:
# Maximum value
# Minimum value
# Mean

matrix = np.random.randint(10,100, size = (4,4))
print(matrix)
print(np.max(matrix))
print(np.min(matrix))
print(np.mean(matrix))

[[67 17 79 82]
 [47 25 88 96]
 [10 95 85 80]
 [47 22 18 50]]
96
10
56.75


In [13]:
# Q11. Student Marks Simulation
# Simulate marks (0–100) of 15 students using np.random.randint()
# Find the top 5 marks (sorted descending).
# Randomly select 3 students for a prize.

np.random.seed(42)

marks = np.random.randint(0,101, size = 15)

top_5 = np.sort(marks)[::-1][:5]

selected_students = np.random.choice(len(marks), size = 3,replace = False)


# print("Marks:",marks)
print("Top 5 marks (decending):",top_5)
# print("Selected student indices:",selected_students)
# print("Selected students marks:",marks[selected_students])

Top 5 marks (decending): [99 92 87 86 82]


In [33]:
# Q12. Daily Sales Data
# Generate daily sales for 7 days between 200 and 1000 units.
# Find the day with the highest sales.
# Randomly pick 2 days for a special offer.
# Shuffle the sales data.

daily_sales = np.random.randint(200,1001, size = 7)

max_day = np.argmax(daily_sales)       
max_sales = daily_sales[max_day]

special_days = np.random.choice(len(daily_sales), size=2, replace=False)

np.random.shuffle(daily_sales)

print(daily_sales)
print(max_sales,max_day)
print(special_days)

[601 676 971 305 902 929 755]
971 1
[0 4]


In [36]:
# Q13. Employee Salary Data
# Create salary data for 8 employees between 30,000 and 80,000.
# Find the employee with the lowest salary.
# Randomly pick 2 employees for a bonus.

salary_data = np.random.randint(30000,80001, size = 8)

min_emp_index = np.argmin(salary_data)

min_salary = salary_data[min_emp_index]

bonus_employees = np.random.choice(len(salary_data), size = 2, replace = False)

print(salary_data)
print(min_salary,min_emp_index)
print(bonus_employees)
print(salary_data[bonus_employees])

[79216 78984 70774 32568 32027 32695 78190 35258]
32027 4
[1 3]
[78984 32568]


In [41]:
# Q14. Product Prices
# You have 10 products. Generate random prices between ₹100 and ₹1000.
# Sort the prices in ascending order.
# Pick 3 random products for a discount.

import numpy as np

np.random.seed(11)

prices = np.random.randint(100, 1001, size=10)

sorted_prices = np.sort(prices)

discount_products = np.random.choice(len(prices), size=3, replace=False)

print(prices)
print(sorted_prices)
print(discount_products)
print(prices[discount_products])

[803 180 191 437 369 432 773 683 950 892]
[180 191 369 432 437 683 773 803 892 950]
[3 1 8]
[437 180 950]


In [14]:
# Q15. Weather Temperature Data
# Simulate 10 random daily temperatures between 25°C and 45°C.
# Find 3 hottest days using argsort().
# Randomly shuffle the temperature data.

import numpy as np

# Set seed for reproducibility (optional but recommended in real projects)
np.random.seed(42)

# 1️⃣ Simulate 10 random daily temperatures between 25°C and 45°C
temps = np.random.randint(25, 46, 10)
print("Daily Temperatures:", temps)

# 2️⃣ Find 3 hottest days using argsort()
# argsort gives indices sorted in ascending order
hottest_indices = np.argsort(temps)[-3:]   # last 3 indices (largest values)
print("Indices of 3 Hottest Days:", hottest_indices)
print("Top 3 Hottest Temperatures:", temps[hottest_indices])

# 3️⃣ Randomly shuffle the temperature data
np.random.shuffle(temps)
print("Shuffled Temperatures:", temps)


Daily Temperatures: [31 44 39 35 32 45 31 43 35 35]
Indices of 3 Hottest Days: [7 1 5]
Top 3 Hottest Temperatures: [43 44 45]
Shuffled Temperatures: [31 31 35 44 35 45 39 35 32 43]


In [15]:
# Q16. Exam Simulation
# You are simulating marks of 1000 students (0–100).
# Find the average mark.
# Find how many scored above 80.
# Randomly select 10 for interview.

import numpy as np

# Reproducibility (important in analytics work)
np.random.seed(42)

# 1️⃣ Simulate marks of 1000 students (0–100 inclusive)
marks = np.random.randint(0, 101, 1000)

# 2️⃣ Find the average mark
average_mark = np.mean(marks)

# 3️⃣ Count how many scored above 80
above_80_count = np.sum(marks > 80)

# 4️⃣ Randomly select 10 students for interview (without replacement)
selected_students = np.random.choice(len(marks), 10, replace=False)

print("Average Mark:", average_mark)
print("Number of Students Scored Above 80:", above_80_count)
print("Selected Student Indices for Interview:", selected_students)
print("Their Marks:", marks[selected_students])


Average Mark: 49.937
Number of Students Scored Above 80: 215
Selected Student Indices for Interview: [953 488 611 514 413 204 538 482 398 677]
Their Marks: [89 22 61 28 47 61 51 57 66  8]


In [16]:
# Q17. Random Sampling in Population
# Create an array representing 1000 people IDs (1–1000).
# Randomly select 50 people for a survey (no repetition).
# Randomly select 5 people for a prize (with repetition).

import numpy as np

# Reproducibility (important in analytics experiments)
np.random.seed(42)

# 1️⃣ Create array of 1000 people IDs (1–1000)
people_ids = np.arange(1, 1001)

# 2️⃣ Randomly select 50 people for survey (no repetition)
survey_sample = np.random.choice(people_ids, 50, replace=False)

# 3️⃣ Randomly select 5 people for prize (with repetition allowed)
prize_sample = np.random.choice(people_ids, 5, replace=True)

print("Survey Sample (50 unique people):")
print(survey_sample)

print("\nPrize Winners (duplicates possible):")
print(prize_sample)


Survey Sample (50 unique people):
[522 738 741 661 412 679 627 514 860 137 812  77 637 974 939 900 281 884
 762 320 550 175 372 528 211 236 102 987 903 948 347 140 622 500 371 199
 688 585 902  60 329  97 313 975 300 278 925 602 440 838]

Prize Winners (duplicates possible):
[172 898  13 168 642]


In [17]:
# Q18. Game Simulation
# A dice game is played 10 times.
# Simulate the results using np.random.randint(1, 7, 10).
# Find how many times 6 appeared.

import numpy as np

# Reproducibility (optional but recommended)
np.random.seed(42)

# 1️⃣ Simulate dice rolled 10 times (1 to 6)
dice_rolls = np.random.randint(1, 7, 10)

# 2️⃣ Count how many times 6 appeared
six_count = np.sum(dice_rolls == 6)

print("Dice Rolls:", dice_rolls)
print("Number of times 6 appeared:", six_count)


Dice Rolls: [4 5 3 5 5 2 3 3 3 5]
Number of times 6 appeared: 0


In [ ]:
import numpy as np


# 0-1

arr=np.random.rand(2,3,4,3,6)
print(arr)


arr=np.random.randint(10,100,size=100)
print(arr)

# normal distribution
arr=np.random.randn(2,3,5)
print(arr)


arr=np.array([10,20,30,40,50])

print(np.random.choice(arr,size=3,replace=False))


arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

np.random.seed(6)
print(np.random.randint(1,50,size=5))

[11 10 36 21 43]
