In [3]:
import numpy as np


# arr=np.array([1,2,3,4,5])

# converted=arr.astype('bool')
# print(converted)

[ True  True  True  True  True]


In [13]:
# arr=np.array([1,2,3,4,5,6])

# print(arr.size)

# reshaped=arr.reshape(3,-1)
# print(reshaped)


# arr=np.array([[2,3,4,5],[6,7,8,9]])
# conv=arr.reshape(-1)
# print(conv)

[2 3 4 5 6 7 8 9]


In [14]:
arr=np.array([[2,3,4,5],[6,7,8,9]])

flattend=arr.flatten()
print(flattend)

[2 3 4 5 6 7 8 9]


In [16]:
arr=np.array([[2,3,4,5],[6,7,8,9]])

print(arr.ravel())


[2 3 4 5 6 7 8 9]


In [18]:
arr=np.array([1,2,3,4,5,6])

arr.resize(2,6)
print(arr)

[[1 2 3 4 5 6]
 [0 0 0 0 0 0]]
