In [1]:
import numpy as np

In [6]:
arr=np.random.randint(1,100,size=(5,7,6))
arr

array([[[ 8, 14, 28, 75, 31, 77],
        [32, 73, 59, 53, 91, 89],
        [44,  6, 71, 63, 98, 66],
        [40, 64, 43, 35, 31, 65],
        [ 1, 96, 36, 40, 98, 66],
        [36, 61,  9, 16, 32, 89],
        [63, 31,  7, 99, 43, 90]],

       [[29, 64, 63, 95,  3, 59],
        [ 2, 11, 19, 70, 50, 63],
        [75, 32, 85, 78, 68, 95],
        [92, 79, 66, 81, 21, 26],
        [91, 41,  5, 29,  9, 40],
        [27, 72, 64, 92,  9, 43],
        [15, 57, 41, 61, 25, 37]],

       [[68, 10, 25, 90, 48, 54],
        [90, 55, 21,  5, 73, 39],
        [87, 46, 53,  6, 36, 10],
        [47, 85, 35, 29, 96, 51],
        [97, 57, 94, 64, 92, 20],
        [63, 72, 56, 82, 91,  6],
        [71, 83,  4, 38, 86, 81]],

       [[69, 29, 15, 78, 24, 56],
        [35, 75, 20,  3, 13, 42],
        [13, 36, 26, 61, 59, 36],
        [ 3, 79, 93,  7, 15, 74],
        [23, 77, 57, 62,  3, 47],
        [26, 41, 43, 17,  2, 29],
        [ 2, 81, 18, 56, 39, 30]],

       [[21, 26, 81, 56, 13,  7],
      

In [8]:
arr=np.random.rand(10,4)
arr

array([[0.73190462, 0.68503064, 0.37377164, 0.58222622],
       [0.58171082, 0.13433309, 0.69581356, 0.10351852],
       [0.61621215, 0.25801317, 0.97455525, 0.1312495 ],
       [0.523924  , 0.62080425, 0.29554013, 0.47371023],
       [0.57996954, 0.17451961, 0.77786102, 0.96078979],
       [0.2916474 , 0.51752562, 0.79193164, 0.10693869],
       [0.61970163, 0.48120604, 0.22201969, 0.35344999],
       [0.90793157, 0.35909488, 0.24453081, 0.34236847],
       [0.20767842, 0.05028755, 0.30490277, 0.7332444 ],
       [0.17845202, 0.23534658, 0.12409177, 0.25911104]])

In [9]:
arr=np.random.randn(500)
arr


array([-7.76082198e-01,  1.21673505e+00, -1.11690553e+00,  8.80084641e-01,
        7.14420010e-01,  6.03812596e-02, -1.62902439e-01, -1.03681836e+00,
       -2.46884466e-01,  8.54228627e-02, -1.25450527e+00, -1.10350983e+00,
       -1.05568031e+00,  2.21293844e+00, -3.32747063e-01, -2.34921437e+00,
       -4.21924613e-01,  1.37142678e+00, -1.75664406e-01, -5.32563552e-01,
       -4.77000679e-01, -1.07803512e+00,  6.22659651e-02,  6.07533267e-01,
        2.01067889e-01, -2.65352259e-01, -4.72431619e-01,  8.43457199e-01,
        2.59452177e-01,  5.97362070e-01,  2.12720324e+00,  7.75844893e-01,
        2.31326016e+00,  2.43911802e-01, -1.72288851e+00,  1.42681735e+00,
        2.06022713e+00, -3.67766277e-01, -1.09250298e+00,  3.15948992e-01,
       -9.26980645e-01, -7.35767302e-01,  4.46883882e-01,  1.15391617e+00,
        8.97549019e-01,  1.21652790e+00, -1.96604169e-02,  1.35132367e+00,
        5.46606271e-01, -1.84397737e+00, -2.16965732e+00,  1.21178235e+00,
       -6.78958009e-01, -

In [16]:
arr=np.array([1,2,3,4,5])

result=np.random.choice(arr,4)
result




array([5, 5, 1, 5])

In [47]:
arr=np.array([1,2,3,4,5])

result=np.random.random_sample(arr,2)
result



TypeError: random_sample() takes at most 1 positional argument (2 given)

In [36]:
np.random.seed(41)

print(np.random.randint(1,100,size=50))


[65 36 13 99 81 66 90 24 86 27 57  4 36 51 71 85 87 62 52 93 89 76 93 53
 56 18 99 82 29 54 20 14 62 96 35 59  5 60  2 77 13 36  5 70 21  6 45 23
 35 47]


In [38]:
arr=np.array([10,20,30,40])

result=np.mean(arr)
result

25.0

In [39]:
arr=np.array([12,34,56,67])
mid=np.median(arr)
print(mid)

45.0


In [45]:
from scipy import stats

arr=np.array([12,34,56,78,12])
# result=stats.mode(arr)
# result=np.unique(arr)
# result=np.min(arr)
# result=np.max(arr)
result

78